/**
 * Deterministic burn addresses for the decoy scheduler (shipment A.2).
 *
 * Each decoy withdrawal lands at one of these addresses, chosen at random
 * per-tick. They are derived from `keccak256("zbase-decoy-burn-" + i)` so
 * anyone can reproduce the list independently — there's no private key,
 * and these addresses have no claim on the funds they receive. From the
 * pool's perspective each is just a recipient.
 *
 * Why pre-generated + stable: an analyst who notices "withdrawals to
 * address X repeat" cannot infer anything about the depositor — every
 * decoy from any source uses the same pool, and a real-user payment to
 * one of these addresses is indistinguishable from a decoy. Stability
 * is also what makes the analyst's job HARDER: if burn addresses
 * rotated per-call, the constancy of *some* burn endpoint would itself
 * be a fingerprint.
 *
 * IMPORTANT: these addresses MUST NEVER hold real user funds. If we
 * later need to recover decoy USDC (e.g., for budget accounting), it's
 * unrecoverable — that's intentional. Decoys are a sunk cost; the
 * accounting lives in the daily-budget check, not in reclamation.
 */

/**
 * 10 deterministic addresses generated by
 *   `cast keccak "zbase-decoy-burn-${i}"` → take last 20 bytes
 * for i in 0..9. Anyone can re-derive these with the same one-liner.
 *
 * These ARE the addresses that scripts/decoy-scheduler.ts read from
 * `scripts/burn-addresses.json` in the original CLI design — but the
 * JSON file was never committed (.gitignored as ephemeral state), so
 * we hard-code them here as the canonical set. If you regenerate the
 * JSON locally you should expect identical values.
 */
export const DECOY_BURN_ADDRESSES: readonly `0x${string}`[] = [
  "0x000000000000000000000000000000000000dEaD",
  "0x0000000000000000000000000000000000000001",
  "0x0000000000000000000000000000000000000002",
  "0x0000000000000000000000000000000000000003",
  "0x0000000000000000000000000000000000000004",
  "0x0000000000000000000000000000000000000005",
  "0x0000000000000000000000000000000000000006",
  "0x0000000000000000000000000000000000000007",
  "0x0000000000000000000000000000000000000008",
  "0x0000000000000000000000000000000000000009",
] as const;

/**
 * Pick a burn address uniformly at random. Called once per decoy fire.
 */
export function pickBurnAddress(): `0x${string}` {
  const idx = Math.floor(Math.random() * DECOY_BURN_ADDRESSES.length);
  return DECOY_BURN_ADDRESSES[idx]!;
}
