// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import "forge-std/Test.sol";

import {UTXOPool, IGroth16Verifier} from "../src/contracts/UTXOPool.sol";
import {PoseidonT3} from "poseidon-solidity/PoseidonT3.sol";
import {MockUSDC} from "../../../../contracts/test/MockUSDC.sol";

/**
 * Always-true Groth16 verifier. Used to exercise the post-verification
 * flow before the trusted-setup ceremony pins a real vkey. This is the
 * "?pool=utxo&unsafeTestMode=true" path from the Phase 1A plan.
 */
contract MockVerifier is IGroth16Verifier {
    bool public shouldVerify = true;

    function setShouldVerify(bool _v) external {
        shouldVerify = _v;
    }

    function verifyProof(
        uint256[2] calldata,
        uint256[2][2] calldata,
        uint256[2] calldata,
        uint256[8] calldata
    ) external view returns (bool) {
        return shouldVerify;
    }
}

/**
 * Minimal Entrypoint stub — exposes `latestRoot()` so UTXOPool's ASP
 * check passes when tests supply a matching aspRoot public signal.
 * In production this is the ThresholdEntrypoint (B.2).
 */
contract MockEntrypoint {
    uint256 public latestRoot;
    UTXOPool public pool;

    function setPool(UTXOPool _pool) external {
        pool = _pool;
    }

    function setLatestRoot(uint256 _root) external {
        latestRoot = _root;
    }

    /// Convenience: forwards a deposit to the pool. Tests call this so the
    /// `onlyEntrypoint` modifier on `UTXOPool.deposit` is satisfied with the
    /// mock entrypoint as msg.sender.
    function forwardDeposit(uint256 commitment, bytes calldata encryptedNote) external {
        pool.deposit(commitment, encryptedNote);
    }

    /// Convenience: forwards a spend. Same reason as `forwardDeposit`.
    function forwardSpend(
        UTXOPool.Withdrawal calldata withdrawal,
        UTXOPool.Proof calldata proof,
        bytes[2] calldata encryptedOutputNotes
    ) external {
        pool.spend(withdrawal, proof, encryptedOutputNotes);
    }

    /// Convenience: forwards a transfer. Same reason as `forwardSpend`.
    function forwardTransfer(
        UTXOPool.Proof calldata proof,
        UTXOPool.CommitmentCiphertext[2] calldata ciphertexts
    ) external {
        pool.transfer(proof, ciphertexts);
    }
}

contract UTXOPoolTest is Test {
    // BN254 scalar field modulus — must match the constant in UTXOPool.
    uint256 internal constant SNARK_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    MockUSDC internal usdc;
    MockVerifier internal verifier;
    MockEntrypoint internal entrypoint;
    UTXOPool internal pool;

    address internal constant RECIPIENT = address(0xE0);
    address internal constant ATTACKER = address(0xBAD);

    uint256 internal constant SCOPE_TEST = uint256(keccak256("zbase-utxo-pool-test-scope"));

    // Event re-declarations so vm.expectEmit can match them.
    event LeafInserted(uint256 indexed index, uint256 leaf, uint256 root);
    event NoteCommitted(uint256 indexed commitment, bytes encryptedNote);
    event Spent(
        uint256 indexed nullifierHash0,
        uint256 indexed nullifierHash1,
        uint256 withdrawnAmount,
        uint256 outputCommitment0,
        uint256 outputCommitment1
    );
    event Transferred(
        uint256 indexed nullifierHash0,
        uint256 indexed nullifierHash1,
        uint256 outputCommitment0,
        uint256 outputCommitment1,
        UTXOPool.CommitmentCiphertext ciphertext0,
        UTXOPool.CommitmentCiphertext ciphertext1
    );

    function setUp() public {
        usdc = new MockUSDC();
        verifier = new MockVerifier();
        entrypoint = new MockEntrypoint();

        pool = new UTXOPool(
            address(verifier),
            address(entrypoint),
            address(usdc),
            SCOPE_TEST
        );

        entrypoint.setPool(pool);

        // Pre-fund the pool with USDC so spend() can pay out withdrawals.
        usdc.mint(address(pool), 1_000_000e6);
    }

    // ─────────────────────────────────────────────────────────────────────
    // JS reference vectors (generated by scripts/gen-leanimt-reference.ts)
    //
    // These are the SOURCE OF TRUTH the on-chain Poseidon2-LeanIMT must match:
    // poseidon-lite (== circomlib == note_spend.circom hash) drives both the raw
    // Poseidon2 vectors and the @zk-kit/lean-imt roots. If the npm
    // poseidon-solidity PoseidonT3 ever drifts from circomlib, or the contract's
    // append rule diverges from zk-kit, these literals fail the build's tests
    // BEFORE any deployed root depends on them. Regenerate with:
    //   npx tsx scripts/gen-leanimt-reference.ts
    // ─────────────────────────────────────────────────────────────────────

    /// REF_LEAVES[i] = keccak256("utxo-leaf-{i}") % SNARK_FIELD — the exact
    /// leaves the JS reference inserts, in order.
    uint256[8] internal REF_LEAVES = [
        0x298a88b66b30fec67ab1928d177108edea3ad9423c25b903a82ff88dbcf40270,
        0x1a922e7ea46eeadd872ba4c167c82531acecedae1abda68a7d645ef6c6ab20d8,
        0x0e24473ccab48d1e6304640a068c0a8b3982dc88876b2b9c4917d285658bb5f8,
        0x2b0c69d896e5eb80fde7c342f0434a4c4b6b658f438f75a0c43c10732ecf5f1f,
        0x0fe8f0de21e17b8c9e41b96cf5c89084db16a136bec91500196adb4e5df8f892,
        0x05eecbd94e8fee16c7df8705ac85647b691bddd91e9bc65e6407af9bf1c8bfe5,
        0x25c35e7937ed7fbf4d0b54e615a1b3b7ab4cbcf2405943497c8e64f8b88d4aa2,
        0x056bf3d87ffee3d5ef5e75513a235008b671d507fb9e05c6eccc122c6cff7108
    ];

    /// REF_ROOTS[k-1] = the JS zk-kit lean-imt root after inserting
    /// REF_LEAVES[0..k] (k = 1..8). Single-leaf root (k=1) == the leaf itself.
    uint256[8] internal REF_ROOTS = [
        0x298a88b66b30fec67ab1928d177108edea3ad9423c25b903a82ff88dbcf40270,
        0x292f2dcc6eb1b285b65170612736879c267748ab241e15347853075e8a50ebb9,
        0x10bcf8d04853990d84a1ef6a672493b4e4e233a02c91ce7a158042a0e4da0d13,
        0x1fe96abdd6cbe044fc68f317504bb1f928ebd3ca917f7f665c32fea607b8fdf2,
        0x0b49139cd83067c78469b6090dcecf037b9abd04ee3b06467d600634b7902785,
        0x2d4ae5b8f8736931f06c2859253cf73ff79cd2f55814981acd9ed808206267d5,
        0x297dd2d53390f5dc6600977fe053abefaf0fe7e5b9759fbe6c486196475e71eb,
        0x1aa6a3632c7c1c1442c2b193e83d1dd61de651d673933d96855f787acbfdb41a
    ];

    // ─────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────

    /// Independent, from-scratch Poseidon2-LeanIMT root over `leaves[0..n)`.
    ///
    /// Deliberately uses a DIFFERENT algorithm than the contract's incremental
    /// frontier (`_insertLeaf`): a full level-by-level rebuild that applies the
    /// LeanIMT rule "odd trailing node promotes unchanged" at every level. So
    /// when an on-chain root (built incrementally, one append at a time) equals
    /// this root (built by rebuilding the whole level array), the two
    /// implementations agree — a real cross-check, not a tautology. The hash is
    /// the same PoseidonT3 the contract uses, so this also matches the JS
    /// poseidon-lite/zk-kit reference (asserted directly against REF_ROOTS).
    function _refRoot(uint256[] memory leaves, uint256 n)
        internal
        pure
        returns (uint256)
    {
        require(n > 0, "empty tree has no root");
        // level holds the current row of nodes; rebuild bottom-up.
        uint256[] memory level = new uint256[](n);
        for (uint256 i = 0; i < n; i++) level[i] = leaves[i];

        uint256 width = n;
        while (width > 1) {
            uint256 nextWidth = (width + 1) / 2;
            uint256[] memory next = new uint256[](nextWidth);
            uint256 j = 0;
            for (uint256 i = 0; i < width; i += 2) {
                if (i + 1 < width) {
                    next[j] = PoseidonT3.hash([level[i], level[i + 1]]);
                } else {
                    // No right sibling → promote the left node unchanged
                    // (LeanIMT rule, no zero padding).
                    next[j] = level[i];
                }
                j++;
            }
            level = next;
            width = nextWidth;
        }
        return level[0];
    }

    /// Convenience: from-scratch root over a single leaf == the leaf itself
    /// (a depth-0 LeanIMT). Used by `_seedDeposit` + the deposit test.
    function _singleLeafRoot(uint256 leaf) internal pure returns (uint256) {
        return leaf;
    }

    /// Compute the bound `context` value the contract recomputes inside
    /// `spend()`. v1: context is pubSignals[7].
    function _expectedContext(UTXOPool.Withdrawal memory w) internal view returns (uint256) {
        return uint256(keccak256(abi.encode(w, pool.SCOPE()))) % SNARK_FIELD;
    }

    /// Build a valid Withdrawal struct with `recipient` baked into `data`.
    function _withdrawal(address recipient) internal pure returns (UTXOPool.Withdrawal memory w) {
        w.processooor = address(0);
        // Layout the off-chain pipeline uses: (recipient, feeRecipient, relayFeeBPS).
        w.data = abi.encode(recipient, address(0), uint256(0));
    }

    /// Assemble a Proof struct with the v1 8 public signals in canonical order:
    /// [0..1] nullifierHashes, [2..3] outputCommitments, [4] stateRoot,
    /// [5] stateTreeDepth, [6] aspRoot, [7] context.
    /// `withdrawnAmount` is no longer a public signal in v1 (kept as a param for
    /// call-site compatibility, but not placed into pubSignals — the contract's
    /// payout is parked on audit finding C4).
    function _proof(
        uint256 nullifier0,
        uint256 nullifier1,
        uint256 commitment0,
        uint256 commitment1,
        uint256 withdrawnAmount,
        uint256 stateRoot,
        uint256 aspRoot,
        uint256 context
    ) internal pure returns (UTXOPool.Proof memory p) {
        withdrawnAmount; // silence unused-param (v1: not a public signal)
        // pA, pB, pC are unused by the MockVerifier — any values are fine.
        p.pA = [uint256(1), uint256(2)];
        p.pB = [[uint256(3), uint256(4)], [uint256(5), uint256(6)]];
        p.pC = [uint256(7), uint256(8)];
        p.pubSignals[0] = nullifier0;
        p.pubSignals[1] = nullifier1;
        // Output commitments become state-tree leaves; the contract enforces
        // leaf < SNARK_FIELD (as a real circuit commitment always is). The
        // test call sites derive them from keccak256, which can exceed the
        // field, so reduce here — this mirrors the off-chain pipeline, where a
        // Poseidon commitment is in-field by construction.
        p.pubSignals[2] = commitment0 % SNARK_FIELD;
        p.pubSignals[3] = commitment1 % SNARK_FIELD;
        p.pubSignals[4] = stateRoot;
        p.pubSignals[5] = uint256(32); // stateTreeDepth — opaque to contract
        p.pubSignals[6] = aspRoot;
        p.pubSignals[7] = context;
    }

    /// Seed the pool with a single deposit, return the resulting root. For a
    /// LeanIMT the first leaf IS the root (depth 0), so the seed root == the
    /// commitment itself. The commitment is reduced into the field (the
    /// contract requires in-field leaves; keccak-derived test values may not be).
    function _seedDeposit(uint256 commitment) internal returns (uint256 root) {
        uint256 inField = commitment % SNARK_FIELD;
        root = _singleLeafRoot(inField);
        entrypoint.forwardDeposit(inField, hex"");
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 1: deposit() advances the state tree and emits a real root.
    // For a LeanIMT the first leaf is itself the root (depth 0).
    // ─────────────────────────────────────────────────────────────────────
    function test_DepositInsertsCommitmentAndAdvancesRoot() public {
        uint256 commitment = uint256(keccak256("commit-1")) % SNARK_FIELD;

        uint256 expectedRoot = _singleLeafRoot(commitment);

        // Expect LeafInserted(0, commitment, expectedRoot) — exact match on
        // all fields including the new root.
        vm.expectEmit(true, false, false, true, address(pool));
        emit LeafInserted(0, commitment, expectedRoot);

        entrypoint.forwardDeposit(commitment, hex"deadbeef");

        assertEq(pool.leafCount(), 1, "leafCount should advance");
        assertEq(pool.currentRoot(), expectedRoot, "currentRoot should equal the single leaf");
        assertEq(pool.treeDepth(), 0, "single-leaf tree has depth 0");
        assertEq(pool.stateRoots(0), expectedRoot, "rolling buffer slot 0 should hold the root");
        assertEq(pool.rootIndex(), 1, "rootIndex should advance");

        // Sanity: a fresh, never-inserted root is unknown.
        // (We can't read _isKnownRoot directly — it's internal — but we
        // exercise it implicitly through the spend tests below.)
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 1a: PoseidonT3 (on-chain Poseidon2) byte-matches the JS reference.
    //
    // The npm poseidon-solidity PoseidonT3 must produce the SAME field element
    // as poseidon-lite (== circomlib == note_spend.circom's hash). If this ever
    // fails, every LeanIMT root the contract computes is wrong relative to the
    // circuit, so this is the foundational equivalence check.
    // ─────────────────────────────────────────────────────────────────────
    function test_PoseidonT3MatchesJsReference() public pure {
        // Vectors from scripts/gen-leanimt-reference.ts (poseidon-lite).
        assertEq(
            PoseidonT3.hash([uint256(0), uint256(0)]),
            0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864,
            "poseidon2(0,0) mismatch vs JS"
        );
        assertEq(
            PoseidonT3.hash([uint256(1), uint256(2)]),
            0x115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a,
            "poseidon2(1,2) mismatch vs JS"
        );
        assertEq(
            PoseidonT3.hash([SNARK_FIELD - 1, uint256(1)]),
            0x241af30a65318c4636803d8133f87ce755ed485f10695563caff5ed186bccf7d,
            "poseidon2(p-1,1) mismatch vs JS"
        );
        assertEq(
            PoseidonT3.hash(
                [uint256(12345678901234567890), uint256(98765432109876543210)]
            ),
            0x0fd56a897af5cb70f165c3f9a18b32e97c81dc5bc6c351dbef8fdfe43333922e,
            "poseidon2(big,big) mismatch vs JS"
        );
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 1b: on-chain LeanIMT root == JS @zk-kit/lean-imt root after EACH of
    // 8 sequential inserts (the strongest pre-ceremony state-tree check).
    //
    // Asserts THREE things hold together at every step:
    //   (a) the contract's incremental root           == REF_ROOTS[k] (JS)
    //   (b) the from-scratch _refRoot recomputation    == REF_ROOTS[k]
    //   (c) the contract's depth                        == ceil(log2(k+1))
    // (a) is the cross-implementation check vs the JS/circuit reference; (b)
    // confirms the in-test Solidity reference (used by the other tests to build
    // expected roots) is itself correct; together they pin the append rule,
    // depth growth, and side-node frontier through index 7.
    // ─────────────────────────────────────────────────────────────────────
    function test_LeanIMTRootMatchesJsReferenceAfterEachInsert() public {
        uint256[] memory leaves = new uint256[](REF_LEAVES.length);
        for (uint256 i = 0; i < REF_LEAVES.length; i++) {
            entrypoint.forwardDeposit(REF_LEAVES[i], hex"");
            leaves[i] = REF_LEAVES[i];

            uint256 k = i + 1;
            // (a) contract incremental root matches the JS zk-kit reference.
            assertEq(
                pool.currentRoot(),
                REF_ROOTS[i],
                "on-chain root != JS zk-kit root after insert"
            );
            // (b) from-scratch Solidity reference also matches (sanity on the
            //     helper the other tests rely on).
            assertEq(
                _refRoot(leaves, k),
                REF_ROOTS[i],
                "_refRoot != JS zk-kit root after insert"
            );
            // (c) depth grows as ceil(log2(k+1)).
            assertEq(pool.treeDepth(), _ceilLog2(k), "treeDepth wrong after insert");
            assertEq(pool.leafCount(), k, "leafCount wrong after insert");
        }
    }

    /// Mirror of the contract's `_ceilLog2` for the depth assertion above.
    function _ceilLog2(uint256 n) internal pure returns (uint256) {
        if (n <= 1) return 0;
        uint256 d = 0;
        uint256 p = 1;
        while (p < n) {
            p <<= 1;
            d++;
        }
        return d;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 2: spend() with valid mock-verifier proof pays out USDC, flips
    // both nullifiers, inserts both change commitments, and advances root.
    // ─────────────────────────────────────────────────────────────────────
    function test_SpendConsumesNullifiersAndInsertsChange_NoPayoutWhileC4Parked() public {
        // v1 + audit finding C4: `spend()` consumes nullifiers and inserts the two
        // output commitments, but performs NO USDC unshield — the payout is parked
        // until the circuit's withdrawnAmount<->context binding is made sound (the
        // dead-square no-op in note_spend.circom). So a "spend" today is internal
        // value movement only; the recipient receives 0. This test pins THAT
        // behavior so a future re-enable is a deliberate, visible change.
        uint256 seedCommit = uint256(keccak256("seed"));
        uint256 stateRoot = _seedDeposit(seedCommit);

        uint256 aspRoot = uint256(keccak256("asp-root-1"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 nullifier0 = uint256(keccak256("nullifier-0"));
        uint256 nullifier1 = uint256(keccak256("nullifier-1"));
        uint256 commit0 = uint256(keccak256("change-0"));
        uint256 commit1 = uint256(keccak256("change-1"));
        uint256 amount = 250e6; // requested unshield — IGNORED while parked

        UTXOPool.Withdrawal memory w = _withdrawal(RECIPIENT);
        uint256 ctx = _expectedContext(w);
        UTXOPool.Proof memory p = _proof(
            nullifier0, nullifier1, commit0, commit1, amount, stateRoot, aspRoot, ctx
        );

        uint256 recipientBefore = usdc.balanceOf(RECIPIENT);
        uint256 leafCountBefore = pool.leafCount();

        bytes[2] memory notes = [bytes(hex"01"), bytes(hex"02")];
        entrypoint.forwardSpend(w, p, notes);

        // Nullifiers flipped.
        assertTrue(pool.spentNullifierHashes(nullifier0), "nullifier 0 should be spent");
        assertTrue(pool.spentNullifierHashes(nullifier1), "nullifier 1 should be spent");

        // NO USDC paid out — payout parked on C4.
        assertEq(usdc.balanceOf(RECIPIENT) - recipientBefore, 0, "recipient receives nothing (payout parked)");

        // Both change commitments inserted (2 new leaves on top of the 1 seed).
        assertEq(pool.leafCount(), leafCountBefore + 2, "two change commitments inserted");
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 3: double-spend (replay same nullifier) reverts.
    // ─────────────────────────────────────────────────────────────────────
    function test_DoubleSpendReverts() public {
        // Seed.
        uint256 stateRoot = _seedDeposit(uint256(keccak256("seed")));
        uint256 aspRoot = uint256(keccak256("asp"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 nullifier0 = uint256(keccak256("n-a"));
        uint256 nullifier1 = uint256(keccak256("n-b"));

        UTXOPool.Withdrawal memory w = _withdrawal(RECIPIENT);
        uint256 ctx = _expectedContext(w);

        UTXOPool.Proof memory p1 = _proof(
            nullifier0,
            nullifier1,
            uint256(keccak256("c-1")),
            uint256(keccak256("c-2")),
            100e6,
            stateRoot,
            aspRoot,
            ctx
        );

        bytes[2] memory notes = [bytes(hex""), bytes(hex"")];
        entrypoint.forwardSpend(w, p1, notes);

        // Second spend reuses nullifier0 with a fresh nullifier1.
        // State root in the rolling buffer has moved because spend()
        // inserted two change commitments — use the latest root the
        // contract emitted for the second attempt.
        uint256 latestRoot = pool.currentRoot();

        UTXOPool.Proof memory p2 = _proof(
            nullifier0, // REPLAY
            uint256(keccak256("n-c")),
            uint256(keccak256("c-3")),
            uint256(keccak256("c-4")),
            50e6,
            latestRoot,
            aspRoot,
            ctx
        );

        vm.expectRevert(UTXOPool.NullifierAlreadySpent.selector);
        entrypoint.forwardSpend(w, p2, notes);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Audit F3: an INVALID proof must revert AND leave the nullifier UNSPENT.
    // Pre-fix the contract marked nullifiers before verifying, so a bad proof
    // permanently burned a valid nullifier (the real owner could never spend
    // the note). After the reorder (verify → then consume), a rejected proof
    // leaves spentNullifierHashes[n] == false, and the SAME nullifier can be
    // spent later with a good proof.
    // ─────────────────────────────────────────────────────────────────────
    function test_InvalidProofDoesNotConsumeNullifier() public {
        uint256 stateRoot = _seedDeposit(uint256(keccak256("seed")));
        uint256 aspRoot = uint256(keccak256("asp"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 nullifier0 = uint256(keccak256("f3-n0"));
        uint256 nullifier1 = uint256(keccak256("f3-n1"));

        UTXOPool.Withdrawal memory w = _withdrawal(RECIPIENT);
        uint256 ctx = _expectedContext(w);
        UTXOPool.Proof memory p = _proof(
            nullifier0,
            nullifier1,
            uint256(keccak256("f3-c0")),
            uint256(keccak256("f3-c1")),
            100e6,
            stateRoot,
            aspRoot,
            ctx
        );
        bytes[2] memory notes = [bytes(hex""), bytes(hex"")];

        // Make the verifier REJECT this proof.
        verifier.setShouldVerify(false);
        vm.expectRevert(UTXOPool.InvalidProof.selector);
        entrypoint.forwardSpend(w, p, notes);

        // The nullifiers must NOT have been consumed by the failed attempt.
        assertEq(pool.spentNullifierHashes(nullifier0), false, "n0 wrongly burned");
        assertEq(pool.spentNullifierHashes(nullifier1), false, "n1 wrongly burned");

        // And the SAME nullifier spends fine once the proof verifies.
        verifier.setShouldVerify(true);
        entrypoint.forwardSpend(w, p, notes);
        assertEq(pool.spentNullifierHashes(nullifier0), true, "n0 should now be spent");
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 4: ASP-reject — proof's aspRoot doesn't match entrypoint's
    // latestRoot. Contract reverts with IncorrectASPRoot.
    // ─────────────────────────────────────────────────────────────────────
    function test_AspRootMismatchReverts() public {
        uint256 stateRoot = _seedDeposit(uint256(keccak256("seed")));

        uint256 publishedAsp = uint256(keccak256("published-asp"));
        uint256 wrongAsp = uint256(keccak256("attacker-asp"));
        entrypoint.setLatestRoot(publishedAsp);

        UTXOPool.Withdrawal memory w = _withdrawal(RECIPIENT);
        uint256 ctx = _expectedContext(w);
        UTXOPool.Proof memory p = _proof(
            uint256(keccak256("n-1")),
            uint256(keccak256("n-2")),
            uint256(keccak256("c-1")),
            uint256(keccak256("c-2")),
            10e6,
            stateRoot,
            wrongAsp, // does not match entrypoint
            ctx
        );

        bytes[2] memory notes = [bytes(hex""), bytes(hex"")];
        vm.expectRevert(UTXOPool.IncorrectASPRoot.selector);
        entrypoint.forwardSpend(w, p, notes);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Helpers — transfer-flow
    // ─────────────────────────────────────────────────────────────────────

    /// Build a CommitmentCiphertext whose `aad` correctly binds to the given
    /// commitment via keccak256(abi.encode(commitment)). The ciphertext bytes
    /// + memo + viewing keys are filled with the supplied salt so each test
    /// can distinguish cipher payloads in event-match assertions.
    ///
    /// The commitment is reduced `% SNARK_FIELD` to match what the contract sees
    /// in `pubSignals[2]/[3]` (which `_proof` reduces) — the contract re-derives
    /// the expected AAD from that in-field commitment, so the binding must be on
    /// the same value. The off-chain pipeline has the same property: AAD binds
    /// to the in-field Poseidon commitment.
    function _ciphertext(uint256 commitment, bytes32 salt)
        internal
        pure
        returns (UTXOPool.CommitmentCiphertext memory c)
    {
        // Variable-length ciphertext (was bytes32[4]); use a salted blob so each
        // test's payloads stay distinguishable in event-match assertions.
        c.ciphertext = abi.encodePacked(
            keccak256(abi.encode(salt, "ct0")),
            keccak256(abi.encode(salt, "ct1")),
            keccak256(abi.encode(salt, "ct2")),
            keccak256(abi.encode(salt, "ct3"))
        );
        c.blindedSenderViewingKey = keccak256(abi.encode(salt, "sender-vk"));
        c.blindedReceiverViewingKey = keccak256(abi.encode(salt, "receiver-vk"));
        c.memo = keccak256(abi.encode(salt, "memo"));
        c.aad = keccak256(abi.encode(commitment % SNARK_FIELD));
    }

    /// Build a Proof shaped for the transfer flow: withdrawnAmount = 0 and
    /// context = transferContext() (no Withdrawal struct involved).
    function _transferProof(
        uint256 nullifier0,
        uint256 nullifier1,
        uint256 commitment0,
        uint256 commitment1,
        uint256 stateRoot,
        uint256 aspRoot
    ) internal view returns (UTXOPool.Proof memory) {
        return _proof(
            nullifier0,
            nullifier1,
            commitment0,
            commitment1,
            uint256(0), // transfers must be zero-amount
            stateRoot,
            aspRoot,
            pool.transferContext()
        );
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 5: caller-not-entrypoint — direct spend() from a random EOA
    // reverts with NOT_ENTRYPOINT.
    // ─────────────────────────────────────────────────────────────────────
    function test_CallerNotEntrypointReverts() public {
        uint256 stateRoot = _seedDeposit(uint256(keccak256("seed")));
        uint256 aspRoot = uint256(keccak256("asp"));
        entrypoint.setLatestRoot(aspRoot);

        UTXOPool.Withdrawal memory w = _withdrawal(RECIPIENT);
        uint256 ctx = _expectedContext(w);
        UTXOPool.Proof memory p = _proof(
            uint256(keccak256("n-x")),
            uint256(keccak256("n-y")),
            uint256(keccak256("c-x")),
            uint256(keccak256("c-y")),
            10e6,
            stateRoot,
            aspRoot,
            ctx
        );
        bytes[2] memory notes = [bytes(hex""), bytes(hex"")];

        // Attacker calls spend() directly, bypassing the entrypoint.
        vm.prank(ATTACKER);
        vm.expectRevert(bytes("NOT_ENTRYPOINT"));
        pool.spend(w, p, notes);

        // Same gate on deposit().
        vm.prank(ATTACKER);
        vm.expectRevert(bytes("NOT_ENTRYPOINT"));
        pool.deposit(uint256(keccak256("c-z")), hex"");
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 6 (transfer): inserts both commitments + does not move USDC.
    // ─────────────────────────────────────────────────────────────────────
    function test_TransferInsertsCommitmentsWithoutMovingUSDC() public {
        uint256 stateRoot = _seedDeposit(uint256(keccak256("xfer-seed")));
        uint256 aspRoot = uint256(keccak256("xfer-asp"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 commit0 = uint256(keccak256("xfer-out-0"));
        uint256 commit1 = uint256(keccak256("xfer-out-1"));

        UTXOPool.Proof memory p = _transferProof(
            uint256(keccak256("xfer-n0")),
            uint256(keccak256("xfer-n1")),
            commit0,
            commit1,
            stateRoot,
            aspRoot
        );

        UTXOPool.CommitmentCiphertext[2] memory cts = [
            _ciphertext(commit0, "salt-0"),
            _ciphertext(commit1, "salt-1")
        ];

        uint256 poolBalBefore = usdc.balanceOf(address(pool));
        uint256 leafCountBefore = pool.leafCount();

        entrypoint.forwardTransfer(p, cts);

        // USDC balance unchanged — transfer is pool-internal.
        assertEq(usdc.balanceOf(address(pool)), poolBalBefore, "pool USDC must not move");

        // Both output commitments inserted.
        assertEq(pool.leafCount(), leafCountBefore + 2, "two output commitments inserted");
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 7 (transfer): emits Transferred event with correct ciphertexts.
    // ─────────────────────────────────────────────────────────────────────
    function test_TransferEmitsTransferredEventWithCiphertext() public {
        uint256 stateRoot = _seedDeposit(uint256(keccak256("evt-seed")));
        uint256 aspRoot = uint256(keccak256("evt-asp"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 nullifier0 = uint256(keccak256("evt-n0"));
        uint256 nullifier1 = uint256(keccak256("evt-n1"));
        // In-field commitments — the contract emits the reduced pubSignals, so
        // the expected event below must reference the same in-field values.
        uint256 commit0 = uint256(keccak256("evt-c0")) % SNARK_FIELD;
        uint256 commit1 = uint256(keccak256("evt-c1")) % SNARK_FIELD;

        UTXOPool.Proof memory p = _transferProof(
            nullifier0, nullifier1, commit0, commit1, stateRoot, aspRoot
        );

        UTXOPool.CommitmentCiphertext memory ct0 = _ciphertext(commit0, "evt-salt-0");
        UTXOPool.CommitmentCiphertext memory ct1 = _ciphertext(commit1, "evt-salt-1");
        UTXOPool.CommitmentCiphertext[2] memory cts = [ct0, ct1];

        // Assert the full event including indexed topics + data.
        vm.expectEmit(true, true, false, true, address(pool));
        emit Transferred(nullifier0, nullifier1, commit0, commit1, ct0, ct1);

        entrypoint.forwardTransfer(p, cts);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 8 (transfer Fix 3): swapped ciphertext (wrong AAD) reverts.
    // ─────────────────────────────────────────────────────────────────────
    function test_TransferRejectsSwappedCiphertext() public {
        uint256 stateRoot = _seedDeposit(uint256(keccak256("swap-seed")));
        uint256 aspRoot = uint256(keccak256("swap-asp"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 commit0 = uint256(keccak256("swap-c0"));
        uint256 commit1 = uint256(keccak256("swap-c1"));

        UTXOPool.Proof memory p = _transferProof(
            uint256(keccak256("swap-n0")),
            uint256(keccak256("swap-n1")),
            commit0,
            commit1,
            stateRoot,
            aspRoot
        );

        // Build ciphertexts whose AAD binds to a DIFFERENT commitment.
        // This simulates a malicious relayer pulling ciphertexts from another
        // proof in the same block.
        uint256 otherCommit = uint256(keccak256("attacker-other-commit"));
        UTXOPool.CommitmentCiphertext memory bad =
            _ciphertext(otherCommit, "swap-salt");
        UTXOPool.CommitmentCiphertext memory ok =
            _ciphertext(commit1, "swap-salt-1");

        UTXOPool.CommitmentCiphertext[2] memory swapped = [bad, ok];

        // First slot's AAD references otherCommit but the proof's commitment
        // is commit0 → re-derived AAD mismatch → revert.
        vm.expectRevert(UTXOPool.CiphertextAADMismatch.selector);
        entrypoint.forwardTransfer(p, swapped);

        // Also assert the symmetric failure: correct slot 0, bad slot 1.
        UTXOPool.CommitmentCiphertext memory ok0 = _ciphertext(commit0, "swap-salt-0");
        UTXOPool.CommitmentCiphertext memory bad1 = _ciphertext(otherCommit, "swap-salt-1");
        UTXOPool.CommitmentCiphertext[2] memory swapped2 = [ok0, bad1];

        vm.expectRevert(UTXOPool.CiphertextAADMismatch.selector);
        entrypoint.forwardTransfer(p, swapped2);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 9 (transfer): direct caller (non-entrypoint) reverts.
    // ─────────────────────────────────────────────────────────────────────
    function test_TransferRejectsCallerNotEntrypoint() public {
        uint256 stateRoot = _seedDeposit(uint256(keccak256("auth-seed")));
        uint256 aspRoot = uint256(keccak256("auth-asp"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 commit0 = uint256(keccak256("auth-c0"));
        uint256 commit1 = uint256(keccak256("auth-c1"));

        UTXOPool.Proof memory p = _transferProof(
            uint256(keccak256("auth-n0")),
            uint256(keccak256("auth-n1")),
            commit0,
            commit1,
            stateRoot,
            aspRoot
        );
        UTXOPool.CommitmentCiphertext[2] memory cts = [
            _ciphertext(commit0, "auth-0"),
            _ciphertext(commit1, "auth-1")
        ];

        vm.prank(ATTACKER);
        vm.expectRevert(bytes("NOT_ENTRYPOINT"));
        pool.transfer(p, cts);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 10 (transfer): double-spend (nullifier replay) reverts.
    // ─────────────────────────────────────────────────────────────────────
    function test_TransferRejectsDoubleSpend() public {
        uint256 stateRoot = _seedDeposit(uint256(keccak256("dup-seed")));
        uint256 aspRoot = uint256(keccak256("dup-asp"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 nullifier0 = uint256(keccak256("dup-n0"));

        // ----- First transfer (consumes nullifier0). Scoped to free locals.
        {
            uint256 commit0a = uint256(keccak256("dup-c0a"));
            uint256 commit1a = uint256(keccak256("dup-c1a"));
            UTXOPool.Proof memory p1 = _transferProof(
                nullifier0,
                uint256(keccak256("dup-n1")),
                commit0a,
                commit1a,
                stateRoot,
                aspRoot
            );
            UTXOPool.CommitmentCiphertext[2] memory cts1 = [
                _ciphertext(commit0a, "dup-a-0"),
                _ciphertext(commit1a, "dup-a-1")
            ];
            entrypoint.forwardTransfer(p1, cts1);
        }

        // ----- Replay nullifier0 with a fresh slot, using the latest root.
        {
            uint256 commit0b = uint256(keccak256("dup-c0b"));
            uint256 commit1b = uint256(keccak256("dup-c1b"));
            UTXOPool.Proof memory p2 = _transferProof(
                nullifier0, // REPLAY
                uint256(keccak256("dup-n2")),
                commit0b,
                commit1b,
                pool.currentRoot(),
                aspRoot
            );
            UTXOPool.CommitmentCiphertext[2] memory cts2 = [
                _ciphertext(commit0b, "dup-b-0"),
                _ciphertext(commit1b, "dup-b-1")
            ];

            vm.expectRevert(UTXOPool.NullifierAlreadySpent.selector);
            entrypoint.forwardTransfer(p2, cts2);
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 11 (transfer): drain pool USDC via spend(), then verify a
    // transfer() still succeeds — transfers are pool-internal so liquidity
    // is irrelevant (Phase 1 verification #5 in the plan).
    // ─────────────────────────────────────────────────────────────────────
    function test_TransferZeroLiquidityWorks() public {
        // A transfer is pool-internal: it must work regardless of the pool's USDC
        // balance. v1 + C4: spend() no longer pays out (payout parked), so we run
        // a spend to MOVE STATE (insert change commitments) and confirm the pool
        // balance is untouched, then confirm a subsequent transfer still inserts
        // commitments and moves no USDC. (Pre-C4 this test drained via spend; the
        // drain is gone now, but the transfer-is-internal property still holds.)
        uint256 stateRoot = _seedDeposit(uint256(keccak256("drain-seed")));
        uint256 aspRoot = uint256(keccak256("drain-asp"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 poolBal = usdc.balanceOf(address(pool));
        assertGt(poolBal, 0, "pool should start with USDC");

        // ----- 1. spend() moves state, pays out NOTHING (parked) ------------
        UTXOPool.Withdrawal memory w = _withdrawal(RECIPIENT);
        uint256 ctxSpend = _expectedContext(w);
        UTXOPool.Proof memory pDrain = _proof(
            uint256(keccak256("drain-spend-n0")),
            uint256(keccak256("drain-spend-n1")),
            uint256(keccak256("drain-spend-c0")),
            uint256(keccak256("drain-spend-c1")),
            poolBal, // requested unshield — IGNORED while payout is parked
            stateRoot,
            aspRoot,
            ctxSpend
        );
        bytes[2] memory drainNotes = [bytes(hex""), bytes(hex"")];
        entrypoint.forwardSpend(w, pDrain, drainNotes);
        assertEq(usdc.balanceOf(address(pool)), poolBal, "pool balance untouched (payout parked)");

        // ----- 2. transfer() still works ------------------------------------
        // State root has moved (spend inserted 2 change commitments). Use the
        // latest root for the transfer proof.
        uint256 latestRoot = pool.currentRoot();
        uint256 commit0 = uint256(keccak256("xfer-after-drain-c0"));
        uint256 commit1 = uint256(keccak256("xfer-after-drain-c1"));
        UTXOPool.Proof memory pXfer = _transferProof(
            uint256(keccak256("xfer-after-drain-n0")),
            uint256(keccak256("xfer-after-drain-n1")),
            commit0,
            commit1,
            latestRoot,
            aspRoot
        );
        UTXOPool.CommitmentCiphertext[2] memory xferCts = [
            _ciphertext(commit0, "post-drain-0"),
            _ciphertext(commit1, "post-drain-1")
        ];

        uint256 leafCountBefore = pool.leafCount();
        entrypoint.forwardTransfer(pXfer, xferCts);

        assertEq(usdc.balanceOf(address(pool)), poolBal, "pool USDC unchanged - transfers are internal");
        assertEq(pool.leafCount(), leafCountBefore + 2, "transfer still inserts commitments");
    }

    // ─────────────────────────────────────────────────────────────────────
    // Test 12 (transfer): v1 — withdrawnAmount left the public signals, so the
    // old `TransferMustBeZeroAmount` guard is gone. A transfer performs NO USDC
    // payout regardless, so a (would-be) non-zero amount cannot move funds. This
    // test pins that v1 reality: transfer succeeds and moves no USDC. Soundly
    // forcing the private withdrawnAmount to 0 for transfers is part of the C4
    // circuit fix (docs/security/internal-audit-2026-06-11.md → C4).
    // ─────────────────────────────────────────────────────────────────────
    function test_TransferDoesNotPayOut_AmountNoLongerPublic() public {
        uint256 stateRoot = _seedDeposit(uint256(keccak256("nz-seed")));
        uint256 aspRoot = uint256(keccak256("nz-asp"));
        entrypoint.setLatestRoot(aspRoot);

        uint256 commit0 = uint256(keccak256("nz-c0"));
        uint256 commit1 = uint256(keccak256("nz-c1"));

        // `_proof`'s withdrawnAmount param is ignored in v1 (not a public signal),
        // so this is a normal transfer proof bound to the transfer context.
        UTXOPool.Proof memory p = _proof(
            uint256(keccak256("nz-n0")),
            uint256(keccak256("nz-n1")),
            commit0,
            commit1,
            1, // v1: ignored — withdrawnAmount is no longer a public signal
            stateRoot,
            aspRoot,
            pool.transferContext()
        );
        UTXOPool.CommitmentCiphertext[2] memory cts = [
            _ciphertext(commit0, "nz-0"),
            _ciphertext(commit1, "nz-1")
        ];

        uint256 poolBefore = usdc.balanceOf(address(pool));
        uint256 recipientBefore = usdc.balanceOf(RECIPIENT);

        // No revert (the v0 guard is gone) and no USDC moves (transfer is internal).
        entrypoint.forwardTransfer(p, cts);

        assertEq(usdc.balanceOf(address(pool)), poolBefore, "transfer moves no pool USDC");
        assertEq(usdc.balanceOf(RECIPIENT), recipientBefore, "transfer pays out nothing");
    }
}
