/**
 * @zbase-protocol/core — D3 deterministic forwarding notes (Phase 2 / forwarding rail)
 *
 * The forwarding rail lets a bounded relayer deposit inbound funds into the pool
 * ON THE USER'S BEHALF, without ever being able to SPEND them. The mechanism:
 *
 *   - The deposit's (nullifier, secret) are DERIVED DETERMINISTICALLY from the
 *     USER'S OWN HD seed at a per-deposit index — NOT randomly generated by the
 *     relayer. The relayer is given only the resulting `precommitment` (a public
 *     value) so it can call the pool's `deposit()`. It never sees, and cannot
 *     reconstruct, the spend secret — that requires the seed, which never leaves
 *     the user.
 *
 *   - Recovery is SCAN-BY-COMMITMENT (the chosen design, 2026-07-09): the user
 *     re-derives candidate (nullifier, secret) for indices 0..N, computes each
 *     commitment, and matches against the pool's on-chain `Deposited` events.
 *     There is NO shared mutable index to corrupt — the relayer and the user only
 *     ever need to agree on the SEED. Even if the relayer's own index counter
 *     desyncs, the user still finds every note by scanning. This is the property
 *     that makes funds UNLOSABLE to a state desync (the failure class CLAUDE.md's
 *     "cleared localStorage = lost funds" gotcha is about).
 *
 * Circuit ground-truth (see account.ts / commitment.circom):
 *     precommitment = Poseidon(2)([nullifier, secret])
 *     commitment    = Poseidon(3)([value, label, precommitment])
 * Any deviation breaks proof verification, so this file reuses account.ts's
 * `computePrecommitment` / `computeCommitment` rather than re-deriving.
 *
 * Derivation domain: a dedicated BIP44 sub-path SEPARATE from the viewing-key
 * path (viewingKeyHD.ts uses m/44'/60'/0'/0'/i for X25519 viewing keys). The
 * forwarding spend-secret path is m/44'/60'/0'/1'/i so a leaked forwarding note
 * cannot be combined with a sibling viewing key. Each index yields TWO field
 * elements (nullifier, secret) via domain-separated hashing of the node key.
 */

import { HDKey } from "@scure/bip32";
import { mnemonicToSeedSync } from "@scure/bip39";
import { keccak_256 } from "@noble/hashes/sha3";
import {
  SNARK_SCALAR_FIELD,
  computePrecommitment,
  computeCommitment,
  computeNullifierHash,
} from "./account.js";

/**
 * PARENT-KEYED change-note domain tags. Deliberately DISTINCT from the deposit
 * domain (`deriveForwardingNote` hashes an HD node key under `zbase/forwarding/*`),
 * so a change note's field elements share no namespace with any deposit's.
 *
 * This replaces a real fund-loss bug. Change notes used to derive at the parent's
 * HD index + 1 — and `parentIndex + 1` is exactly the slot the NEXT deposit claims
 * (`nextDepositIndex` returns `max(index)+1`). Two live deposits plus a payment
 * from the older one put two notes on the same index → the same nullifier →
 * spending one permanently locked the other. Keying the change note on the
 * PARENT'S SECRETS instead of a shared counter removes the shared namespace
 * entirely, so the collision is impossible by construction. The parent's raw
 * nullifier/secret never appear on-chain (only `Poseidon(nullifier)` does), so
 * only the note's owner can derive its change.
 */
const CHANGE_NULLIFIER_TAG = "zbase/change/nullifier";
const CHANGE_SECRET_TAG = "zbase/change/secret";

/**
 * BIP44 path prefix for forwarding SPEND secrets. Hardened fourth segment `1'`
 * separates this domain from the viewing-key domain (`0'`) — a leaked forwarding
 * note cannot be recombined with a viewing key derived from the same mnemonic.
 *
 *   m / 44' / 60' / 0' / 1' / index
 */
export const ZBASE_FORWARDING_PATH_PREFIX = "m/44'/60'/0'/1'";

/** A deterministically-derived forwarding note's spend secrets + public precommitment. */
export interface ForwardingNoteSecrets {
  /** Per-deposit derivation index. */
  index: number;
  /** Spend nullifier (field element, decimal string). Derived from the seed. */
  nullifier: string;
  /** Spend secret (field element, decimal string). Derived from the seed. */
  secret: string;
  /**
   * `precommitment = Poseidon(2)([nullifier, secret])` — the ONLY value handed to
   * the relayer. Public; reveals nothing about the spend secret.
   */
  precommitment: string;
  /** Full derivation path, e.g. "m/44'/60'/0'/1'/0". */
  derivationPath: string;
}

/**
 * Reduce a 32-byte hash to a BN254 field element via rejection-free modular
 * reduction with domain tagging. The bias from a single `% r` is negligible for
 * a keccak digest domain-separated per (node, tag); we do NOT need the CSPRNG
 * rejection sampling used for random secrets because these values are
 * DETERMINISTIC (reproducibility is the requirement, not perfect uniformity) and
 * keccak output is already ~uniform over 2^256. Determinism is load-bearing:
 * the user must re-derive the EXACT same value to recover the note.
 */
function hashToField(nodeKey: Uint8Array, tag: string): bigint {
  const tagBytes = new TextEncoder().encode(tag);
  const buf = new Uint8Array(nodeKey.length + tagBytes.length);
  buf.set(nodeKey, 0);
  buf.set(tagBytes, nodeKey.length);
  const h = keccak_256(buf);
  let x = 0n;
  for (const b of h) x = (x << 8n) | BigInt(b);
  return x % SNARK_SCALAR_FIELD;
}

/**
 * Derive the forwarding note secrets for a given index from a BIP39 mnemonic.
 *
 * Deterministic and pure: same mnemonic + index → same (nullifier, secret,
 * precommitment), always. This is what lets the user recover a note the relayer
 * deposited, by re-deriving and scanning.
 *
 * @param mnemonic  the user's BIP39 seed phrase (NEVER leaves the client / never sent to the relayer)
 * @param index     per-deposit index (0, 1, 2, …)
 */
export function deriveForwardingNote(
  mnemonic: string,
  index: number,
): ForwardingNoteSecrets {
  if (!Number.isInteger(index) || index < 0) {
    throw new Error("deriveForwardingNote: index must be a non-negative integer");
  }
  const seed = mnemonicToSeedSync(mnemonic);
  const root = HDKey.fromMasterSeed(seed);
  const path = `${ZBASE_FORWARDING_PATH_PREFIX}/${index}`;
  const node = root.derive(path);
  if (!node.privateKey) {
    throw new Error("deriveForwardingNote: derivation produced no private key");
  }
  // Two domain-separated field elements from the same node key.
  const nullifier = hashToField(node.privateKey, "zbase/forwarding/nullifier");
  const secret = hashToField(node.privateKey, "zbase/forwarding/secret");
  const nullifierStr = nullifier.toString();
  const secretStr = secret.toString();
  return {
    index,
    nullifier: nullifierStr,
    secret: secretStr,
    precommitment: computePrecommitment(nullifierStr, secretStr),
    derivationPath: path,
  };
}

/**
 * Relayer-side view: given ONLY the user's PUBLIC precommitment stream is not
 * possible (precommitments require the seed to derive). Instead the relayer is
 * handed a specific `precommitment` for the index it should deposit at — this
 * helper is the USER/CLIENT producing that value to register. The relayer never
 * calls `deriveForwardingNote` (it has no mnemonic); it only ever receives the
 * `precommitment` field.
 *
 * Returned precommitment is safe to transmit to the relayer.
 */
export function precommitmentForRelayer(
  mnemonic: string,
  index: number,
): string {
  return deriveForwardingNote(mnemonic, index).precommitment;
}

/**
 * SCAN-BY-COMMITMENT recovery. Given the user's mnemonic and the set of on-chain
 * `Deposited` events (each carrying commitment, label, value), find which
 * derived notes actually landed on-chain and return the full recoverable notes.
 *
 * This is how the user reclaims funds the relayer deposited: derive candidate
 * notes for indices [0, maxIndex], compute each commitment against the event's
 * (value, label), and match. NO shared index state is needed — only the seed.
 *
 * @param mnemonic       user's seed phrase
 * @param depositedEvents on-chain Deposited events { commitment, label, value }
 * @param maxIndex       highest index to scan (inclusive). Scan a window past the
 *                       last found note to tolerate gaps.
 */
export function recoverForwardingNotes(
  mnemonic: string,
  depositedEvents: Array<{ commitment: string; label: string; value: string }>,
  maxIndex: number,
): Array<ForwardingNoteSecrets & { value: string; label: string; commitment: string }> {
  // Index on-chain commitments for O(1) lookup.
  const byCommitment = new Map<string, { label: string; value: string }>();
  for (const ev of depositedEvents) {
    byCommitment.set(String(ev.commitment), { label: String(ev.label), value: String(ev.value) });
  }

  const found: Array<
    ForwardingNoteSecrets & { value: string; label: string; commitment: string }
  > = [];
  for (let i = 0; i <= maxIndex; i++) {
    const note = deriveForwardingNote(mnemonic, i);
    // For each on-chain event, the commitment is Poseidon3(value, label, precommitment).
    // We can't know (value,label) a priori, so test the note's precommitment against
    // every event's (value,label). In practice the event set is small per user.
    for (const [commitment, { label, value }] of byCommitment) {
      const derivedCommitment = computeCommitment(value, label, note.precommitment);
      if (derivedCommitment === commitment) {
        found.push({ ...note, value, label, commitment });
        break;
      }
    }
  }
  return found;
}

/** 32-byte big-endian encoding of a field element, for parent-keyed hashing. */
function fieldTo32Bytes(v: bigint): Uint8Array {
  const out = new Uint8Array(32);
  let x = v;
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(x & 0xffn);
    x >>= 8n;
  }
  return out;
}

/**
 * Derive a CHANGE note's spend secrets deterministically from the note being spent.
 *
 * Pure function of the parent's `(nullifier, secret)`: same parent → same change,
 * always. Three properties fall out of that:
 *
 *   1. NO COLLISION with deposits — the field elements live in the `zbase/change/*`
 *      hash domain, disjoint from the HD deposit domain. See the tag comment above.
 *   2. A LOST WITHDRAW RESPONSE IS RECOVERABLE from the parent note the caller is
 *      already holding — re-derive, don't reach for a saved copy. This is the direct
 *      fix for the 0.985 USDC loss (random secrets, returned once, dropped).
 *   3. THE WHOLE ROTATION CHAIN rebuilds from the root note alone: `C1 = f(D)`,
 *      `C2 = f(C1)`, … so recovery walks `Withdrawn` events deriving each hop from
 *      its parent, with no index bookkeeping.
 *
 * A note is spent at most once (its nullifier is published exactly once), so a
 * parent has exactly one change note — the mapping is 1:1 and unambiguous.
 */
export function deriveChangeNote(parent: {
  nullifier: string | bigint;
  secret: string | bigint;
}): { nullifier: string; secret: string; precommitment: string } {
  const material = new Uint8Array(64);
  material.set(fieldTo32Bytes(BigInt(parent.nullifier)), 0);
  material.set(fieldTo32Bytes(BigInt(parent.secret)), 32);
  const nullifier = hashToField(material, CHANGE_NULLIFIER_TAG).toString();
  const secret = hashToField(material, CHANGE_SECRET_TAG).toString();
  return {
    nullifier,
    secret,
    precommitment: computePrecommitment(nullifier, secret),
  };
}

/** The minimal spendable fields of a recovered note. */
export interface SpendableNote {
  nullifier: string;
  secret: string;
  value: string;
  label: string;
  commitment: string;
}

/**
 * Recover CHANGE notes from the seed by walking the withdrawal chain.
 *
 * This closes the last recovery gap. Deposits recover directly
 * (`recoverForwardingNotes`); their change notes did not, because a change note's value
 * is in no event of its own. The `Withdrawn` events supply it: each links a spent
 * parent's nullifier hash to the value pushed out and the new (change) commitment.
 *
 * For every recovered parent that was spent, the change is fully reconstructable:
 *   - SECRETS  — `deriveChangeNote(parent)` (parent-keyed; same domain the SDK spends in)
 *   - LABEL    — the parent's (ASP propagation: an output label matches an input label)
 *   - VALUE    — `parent_value − withdrawn_value` (exact; no change-side fee)
 * then VERIFIED against the on-chain `newCommitment`. A match both confirms the leaf is
 * ours and pins the value unambiguously. Because a change note can itself be spent, the
 * walk recurses down the lineage.
 *
 * Only recovers change notes whose secrets were parent-keyed — i.e. spent through the
 * current SDK. A pre-fix legacy random change note has no seed link and cannot be
 * recovered by anything (the already-lost 0.985).
 *
 * @param deposits    recovered parent notes (from `recoverForwardingNotes`)
 * @param withdrawals on-chain `Withdrawn` tuples { value, spentNullifier, newCommitment }
 */
export function recoverChangeNotes(
  deposits: readonly SpendableNote[],
  withdrawals: readonly { value: string; spentNullifier: string; newCommitment: string }[],
): SpendableNote[] {
  // spentNullifierHash → withdrawal. A nullifier is spent once, so this is 1:1.
  const bySpent = new Map<string, { value: string; newCommitment: string }>();
  for (const w of withdrawals) {
    bySpent.set(String(w.spentNullifier), { value: String(w.value), newCommitment: String(w.newCommitment) });
  }

  const recovered: SpendableNote[] = [];
  const seen = new Set<string>(); // guard against any cycle; each nullifier appears once
  // Walk from each recovered deposit down its change lineage.
  let frontier: SpendableNote[] = [...deposits];
  while (frontier.length > 0) {
    const next: SpendableNote[] = [];
    for (const parent of frontier) {
      const nh = computeNullifierHash(parent.nullifier);
      if (seen.has(nh)) continue;
      seen.add(nh);
      const w = bySpent.get(nh);
      if (!w) continue; // this note is unspent — no change note beyond it

      const child = deriveChangeNote(parent);
      const childValue = (BigInt(parent.value) - BigInt(w.value)).toString();
      const childCommitment = computeCommitment(childValue, parent.label, child.precommitment);
      // Verify against chain. A mismatch means this parent did not fund this withdrawal
      // via the parent-keyed path (e.g. a legacy random change) — skip rather than invent.
      if (childCommitment !== String(w.newCommitment)) continue;

      const note: SpendableNote = {
        nullifier: child.nullifier,
        secret: child.secret,
        value: childValue,
        label: parent.label,
        commitment: childCommitment,
      };
      recovered.push(note);
      next.push(note); // the change note may itself have been spent
    }
    frontier = next;
  }
  return recovered;
}
