// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * Minimal Morpho-Blue-style vault interface used by zBase's privacy pool.
 *
 * We only need three pieces of behavior from the underlying yield vault:
 *   1. `supply` — deposit USDC, receive vault tokens (shares) priced in USDC.
 *   2. `previewRedeem` — quote how much USDC `vaultTokens` would redeem for now.
 *   3. `redeem` — burn shares, receive USDC.
 *
 * Real Morpho Blue exposes these via the Singleton + MetaMorpho ERC4626 facade.
 * The pool contract only relies on the abstract shape so we can mock it in tests.
 */
interface IMorphoYieldVault {
    function supply(uint256 assets, address onBehalf) external returns (uint256 sharesMinted);
    function redeem(uint256 shares, address receiver) external returns (uint256 assetsOut);
    function previewRedeem(uint256 shares) external view returns (uint256 assetsOut);
}

/**
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │ ⚠️  NOT DEPLOYED — and the live pool is NOT this contract. Verified       │
 * │     on-chain 2026-06-25: the deployed pool at 0x4ebcfeaf… is a PLAIN      │
 * │     0xbow PrivacyPool (every Morpho/yield getter — morpho/vault/          │
 * │     totalYield/PROTOCOL_FEE_BPS — REVERTS; ASSET() returns raw USDC).     │
 * │     This yield variant was the abandoned STAGING path (src/lib/           │
 * │     contracts.ts header, 2026-06-01): it has no Merkle tree, no Deposited │
 * │     event, and no way to spend commitments back out — it is ONLY the      │
 * │     yield-distribution patch, not a usable privacy pool on its own.       │
 * │                                                                           │
 * │  FUTURE USE (if ever): yield is a deliberately-PARKED feature             │
 * │     (PROTOCOL_FEE_BPS=0, "customer benefit not revenue" — CLAUDE.md). The │
 * │     math doesn't work at agent-TVL scale and adds regulatory category-    │
 * │     creep, so this is NOT planned for mainnet. Mainnet deploys the SAME   │
 * │     plain 0xbow pool (no yield). Kept for reference / a possible high-TVL  │
 * │     future; do NOT deploy without revisiting the yield-spread decision in │
 * │     docs/strategy/revenue-model-recommendation-2026-06-18.md (parked).    │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * PrivacyPoolMorpho — zBase's Morpho-backed privacy pool.
 *
 * This is the on-chain layer of the zBase x402 facilitator. The full upstream
 * contract is a fork of 0xbow Privacy Pools (Apache 2.0, Vitalik-co-authored)
 * with a Morpho-supply/redeem hook on `_pull()` / `_push()`. This file is the
 * **yield-distribution patch** kept inside the zBase repo as the canonical diff
 * to apply to the upstream fork when it is vendored — and it stays compilable +
 * testable on its own so the math can be verified by Foundry today.
 *
 *   _pull()  — called during deposit, after the ZK commitment is inserted.
 *              Approves Morpho for the post-fee value and supplies it.
 *
 *   _push()  — called during a successful relay (withdrawal). Burns the right
 *              number of vault shares, splits the proceeds into principal,
 *              yield-net-of-fee, and protocol fee, and routes them to:
 *                  recipient            → principal + 99% of yield
 *                  PROTOCOL_FEE_RECIPIENT → 1% of yield
 *
 *  Backwards-compatibility note: the on-chain proof verifier signature is NOT
 *  touched. Only the post-verification fund routing changes. Existing Groth16
 *  withdrawal proofs generated by `/api/withdraw` keep verifying identically;
 *  only the USDC delta seen by the recipient changes.
 *
 *  Test-mode behavior: on testnets where Morpho has no real borrowers, the
 *  `previewRedeem(shares) == originalDepositValue` invariant holds and the
 *  fee branch is short-circuited (`yield == 0 → fee == 0`). The depositor is
 *  not charged anything in the no-yield case. This matches INTRO.md:146.
 */
contract PrivacyPoolMorpho is ReentrancyGuard {
    using SafeERC20 for IERC20;

    // ─────────────────────────────────────────────────────────────────────
    // Immutable configuration
    // ─────────────────────────────────────────────────────────────────────

    /// USDC (the only asset this pool accepts).
    IERC20 public immutable USDC;

    /// Morpho vault USDC is supplied into. Set at deploy.
    IMorphoYieldVault public immutable MORPHO_VAULT;

    /// Where the 1% protocol fee on realized yield is sent.
    /// Immutable on purpose: changing the destination would require a
    /// 3-of-5 postman multisig ceremony per CLAUDE.md governance rules.
    address public immutable PROTOCOL_FEE_RECIPIENT;

    /// Authorized caller for `_pull` / `_push`. In production this is the
    /// upstream PrivacyPool contract (or its proxy) which invokes these
    /// hooks from `deposit()` / `relay()` *after* verifying the ZK proof
    /// and inserting/spending the commitment. Anyone else calling `_pull`
    /// directly could move idle pool USDC into Morpho under an attacker-
    /// chosen commitment key (griefing); `_push` directly would let them
    /// drain shares attributed to a known commitment. Locked at deploy
    /// time — pool is operationally immutable so no setter is provided.
    address public immutable ENTRYPOINT;

    /// Protocol fee, in basis points, charged on the *yield* portion only
    /// (never on principal). Currently 0 — yield is a customer benefit, not
    /// a revenue line. The fee-skim path is preserved so a future shipment
    /// can re-enable it (e.g. for an enterprise tier) by changing this
    /// constant and re-deploying. See plan §"Revenue model" for the rationale
    /// (yield-spread was dropped: math doesn't work at agent TVL scale,
    /// conflicts with privacy thesis, triggers regulatory category-creep).
    uint256 public constant PROTOCOL_FEE_BPS = 0;

    /// BPS denominator (10_000 = 100%).
    uint256 public constant BPS_DENOMINATOR = 10_000;

    // ─────────────────────────────────────────────────────────────────────
    // Per-commitment accounting (the bit we need beyond the upstream pool)
    // ─────────────────────────────────────────────────────────────────────

    /// Vault shares attributable to each commitment (keyed by the
    /// Poseidon-hashed commitment). Populated in `_pull`, consumed in `_push`.
    mapping(uint256 => uint256) public sharesByCommitment;

    /// Principal (post-fee USDC value) recorded at deposit time, used as the
    /// "originalDepositValue" baseline when computing realized yield.
    mapping(uint256 => uint256) public principalByCommitment;

    // ─────────────────────────────────────────────────────────────────────
    // Events
    // ─────────────────────────────────────────────────────────────────────

    /// Emitted on every `_pull` so off-chain indexers can track share basis.
    event YieldSupplied(uint256 indexed commitment, uint256 principal, uint256 sharesMinted);

    /// Emitted on every `_push`. `yieldAmount` and `fee` are 0 when there is
    /// no yield (testnet / immediate-withdrawal path).
    event YieldDistributed(
        address indexed recipient,
        uint256 principal,
        uint256 yieldAmount,
        uint256 fee
    );

    // ─────────────────────────────────────────────────────────────────────
    // Constructor
    // ─────────────────────────────────────────────────────────────────────

    constructor(address _usdc, address _morphoVault, address _protocolFeeRecipient) {
        require(_usdc != address(0), "USDC=0");
        require(_morphoVault != address(0), "MORPHO=0");
        require(_protocolFeeRecipient != address(0), "FEE_RECIPIENT=0");

        USDC = IERC20(_usdc);
        MORPHO_VAULT = IMorphoYieldVault(_morphoVault);
        PROTOCOL_FEE_RECIPIENT = _protocolFeeRecipient;

        // Lock _pull/_push to the deployer. In production the deployer is
        // the upstream PrivacyPool contract; in Foundry tests the deployer
        // is the test contract itself, so existing assertions keep working
        // without a special wrapper. Codex P2 fix: previously _pull / _push
        // were unconditionally external, letting any account drive Morpho
        // supply/redeem against arbitrary commitment keys on the deployed
        // contract.
        ENTRYPOINT = msg.sender;

        // Approve the vault for max so each `_pull` doesn't pay an SSTORE.
        // Safe because the only path that calls `MORPHO_VAULT.supply` is
        // `_pull`, and `_pull` is only callable by ENTRYPOINT (in
        // production: the upstream `deposit` flow; in tests: the test
        // contract that deployed the pool).
        IERC20(_usdc).forceApprove(_morphoVault, type(uint256).max);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Access control
    // ─────────────────────────────────────────────────────────────────────

    modifier onlyEntrypoint() {
        require(msg.sender == ENTRYPOINT, "NOT_ENTRYPOINT");
        _;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Deposit-side hook (exposed for tests + the eventual upstream override)
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Internal hook the upstream `deposit()` calls after pulling USDC from
     * the depositor and inserting the commitment into the Merkle tree.
     *
     * `commitment` is the Poseidon(value, label, precommitment) hash already
     * verified by the upstream contract.
     * `postFeeValue` is what the upstream contract pre-computes after the 1%
     * vetting fee (the "990000 for a 1 USDC deposit" gotcha in CLAUDE.md).
     *
     * Marked `public` here only so tests can drive it; in the upstream merge
     * this becomes `internal override`. Gated to `onlyEntrypoint` so that on
     * the deployed contract only the upstream PrivacyPool (which is set as
     * ENTRYPOINT via the deployer = msg.sender pattern in the constructor)
     * can move idle pool USDC into Morpho under a chosen commitment key.
     */
    function _pull(uint256 commitment, uint256 postFeeValue) public onlyEntrypoint nonReentrant {
        require(principalByCommitment[commitment] == 0, "ALREADY_PULLED");
        require(postFeeValue > 0, "ZERO_VALUE");

        uint256 sharesMinted = MORPHO_VAULT.supply(postFeeValue, address(this));

        sharesByCommitment[commitment] = sharesMinted;
        principalByCommitment[commitment] = postFeeValue;

        emit YieldSupplied(commitment, postFeeValue, sharesMinted);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Withdraw-side hook — the load-bearing change in this patch
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Internal hook called from `relay()` after the Groth16 proof has been
     * verified, the nullifier marked spent, and the change commitment
     * inserted into the state tree.
     *
     *   commitment       — the spent note's commitment (used to look up shares).
     *   withdrawnValue   — how much of the note value the user is taking out.
     *                       The upstream pool computes this from the proof's
     *                       public signals; this contract trusts it.
     *   recipient        — the on-chain payee from the withdrawal's relay data.
     *
     * The contract redeems exactly the share-portion that corresponds to
     * `withdrawnValue`, then splits the proceeds:
     *
     *   currentValue  = previewRedeem(shareSlice)
     *   yield         = currentValue - withdrawnValue                 (if > 0)
     *   fee           = yield * PROTOCOL_FEE_BPS / BPS_DENOMINATOR
     *   payout        = currentValue - fee
     *
     * When `currentValue <= withdrawnValue` (idle pool, testnet, or rounding-
     * down by Morpho) the fee path is skipped entirely.
     *
     * Marked `public` only so tests can drive it; in upstream this is
     * `internal override`. Same `onlyEntrypoint` gate as `_pull` — an
     * unrestricted public `_push` on the deployed contract would let any
     * caller redeem shares attributed to a known commitment to an
     * attacker-controlled `recipient`.
     */
    function _push(uint256 commitment, uint256 withdrawnValue, address recipient)
        public
        onlyEntrypoint
        nonReentrant
    {
        require(recipient != address(0), "RECIPIENT=0");
        require(withdrawnValue > 0, "ZERO_WITHDRAW");

        uint256 totalShares = sharesByCommitment[commitment];
        uint256 principal = principalByCommitment[commitment];
        require(totalShares > 0 && principal > 0, "UNKNOWN_COMMITMENT");
        require(withdrawnValue <= principal, "OVER_WITHDRAW");

        // Proportional share slice for a partial withdrawal. For a full
        // withdrawal (withdrawnValue == principal) this is just totalShares.
        uint256 sharesToRedeem = (totalShares * withdrawnValue) / principal;
        require(sharesToRedeem > 0, "DUST_REDEEM");

        // F13: decrement principal by the slice that MATCHES the shares actually
        // burned, not by the requested withdrawnValue. Pre-fix, principal was
        // reduced by withdrawnValue while only `sharesToRedeem` shares (a rounded-
        // down slice) left — so across many partial withdrawals the remaining
        // principal could overstate the USDC still backing the note, leaving a
        // late withdrawer underfunded. Using the share-proportional principal
        // keeps remaining principal consistent with remaining shares. For a full
        // withdrawal sharesToRedeem == totalShares, so principalRedeemed ==
        // principal and the note zeroes out exactly.
        uint256 principalRedeemed = (principal * sharesToRedeem) / totalShares;
        if (principalRedeemed == 0) principalRedeemed = withdrawnValue; // safety floor

        // Burn shares → receive USDC into this contract.
        uint256 currentValue = MORPHO_VAULT.redeem(sharesToRedeem, address(this));

        // Update per-commitment accounting *before* external transfers.
        sharesByCommitment[commitment] = totalShares - sharesToRedeem;
        principalByCommitment[commitment] =
            principalRedeemed >= principal ? 0 : principal - principalRedeemed;

        uint256 yieldAmount;
        uint256 fee;
        uint256 payout;

        if (currentValue > withdrawnValue) {
            // Yield branch (mainnet, real Morpho APY).
            yieldAmount = currentValue - withdrawnValue;
            fee = (yieldAmount * PROTOCOL_FEE_BPS) / BPS_DENOMINATOR;
            payout = currentValue - fee;

            if (fee > 0) {
                USDC.safeTransfer(PROTOCOL_FEE_RECIPIENT, fee);
            }
        } else {
            // No-yield branch (testnet, immediate withdraw, or Morpho rounding
            // down). Pay out exactly what we got back; no fee.
            yieldAmount = 0;
            fee = 0;
            payout = currentValue;
        }

        USDC.safeTransfer(recipient, payout);

        emit YieldDistributed(recipient, withdrawnValue, yieldAmount, fee);
    }
}
