[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
zx402_privacy_pool = "7qGhxY9Dc9reSNbNHdX1Rtf7hq7D45zdnV1UY3rpt3eM"
zx402_native_receiver = "8NZ1DwqbnTuTR2k1mAmsRFxQHBYkQgYs5UHaGD7onAmy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.devnet]
zx402_privacy_pool = "7qGhxY9Dc9reSNbNHdX1Rtf7hq7D45zdnV1UY3rpt3eM"
