// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {PoseidonT3} from "poseidon-solidity/PoseidonT3.sol";

/**
 * @title UTXOPool — variable-amount UTXO-note privacy pool (Shipment A.1, v1)
 * @author zBase eng, 2026-05-29 (Phase 1A wiring 2026-06-09; Phase 2 Poseidon-LeanIMT 2026-06-16)
 *
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │ ⚠️  NOT DEPLOYED — anywhere (no testnet, no mainnet) as of 2026-06-25.    │
 * │     `UTXO_STACK` in src/lib/contracts.ts is all 0x0; `?pool=utxo` routes  │
 * │     return 501 ("ceremony_pending"). This is the live single-value pool's │
 * │     amount-hiding successor, but it is DEFERRED, not on the critical path. │
 * │                                                                           │
 * │  WHEN/HOW this deploys (future):                                          │
 * │   - TESTNET demo: solo throwaway ceremony → deploy → fill UTXO_STACK.     │
 * │       Runbook: docs/release/utxo-testnet-runbook.md                       │
 * │   - MAINNET: blocked on C4 (spend() pays 0 USDC — see §6 below) + B3      │
 * │       (perfect-tree-only) circuit fixes → re-freeze → EXTERNAL AUDIT →    │
 * │       real 15-person ceremony. Do NOT run the real ceremony before C4+B3  │
 * │       (they force a re-freeze = wasted ceremony).                         │
 * │   - GATING DECISION: build only when a NAMED buyer needs amount-hiding.   │
 * │       Adversarial verdict: amount-hiding is NOT the moat (it's 0xbow's    │
 * │       home turf); the moat is the x402 facilitator RAIL. Full reasoning:  │
 * │       docs/strategy/utxo-moat-review-2026-06-25.md                        │
 * │                                                                           │
 * │  The live, deployed, revenue product is the PLAIN 0xbow PrivacyPool       │
 * │  (single-value, NO yield) at 0x4ebcfeaf… — NOT this contract.             │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * Scaffold contract. Pre-ceremony. Replaces the single-value commitment of
 * `PrivacyPoolMorpho` with a 2-input × 2-output UTXO spend. Deployed at a new
 * address; coexists with the legacy single-value pool (different SCOPE = naturally
 * disjoint anonymity sets; migration is opt-in by user round-trip).
 *
 * Design doc: /docs/utxo-notes-design.md
 *
 * What this scaffold pins:
 *  - External API: `spend(...)` parameter layout.
 *  - Public-signal ordering (matches `note_spend.circom`).
 *  - Nullifier / known-state-root bookkeeping rules.
 *  - Event surface (`Spent`, `NoteCommitted`, `LeafInserted`).
 *  - onlyEntrypoint gating + ReentrancyGuard (Phase 1A wiring).
 *  - The canonical Poseidon2-LeanIMT root over inserted leaves (Phase 2 —
 *    see "State tree note" below; equals the JS zk-kit reference root).
 *
 * What this scaffold does NOT implement:
 *  - The actual Groth16 verifier deployment (vkey unknown until ceremony).
 *  - Morpho integration (drop in once vkey is known; reuse PrivacyPoolMorpho's
 *    `_supply`/`_redeem` patterns).
 *  - ASP root acceptance window (today the existing pool requires equality
 *    with `entrypoint.latestRoot`; we may relax to "any root in the rolling
 *    last-N window" once threshold-postman B.2 ships).
 *  - Pausability (mirror existing pool's `Ownable + Pausable`).
 *
 * State tree note (Phase 2, 2026-06-16):
 *   The repo does not vendor a Solidity LeanIMT library; the production
 *   zk-kit lean-imt package is JS-only. This contract now implements the
 *   canonical Poseidon2-LeanIMT incrementally on-chain (`_insertLeaf`): the
 *   parent hash is PoseidonT3.hash (poseidon-solidity, byte-identical to
 *   circomlib / poseidon-lite / `note_spend.circom`), and the append rule
 *   matches zk-kit `LeanIMT.insert` (dynamic depth, "no right sibling →
 *   parent = left child", no zero padding). Each insert advances `currentRoot`
 *   and pushes it into the `STATE_ROOT_HISTORY` rolling buffer.
 *
 *   This produces the SAME root the JS zk-kit reference computes for the same
 *   leaves — UTXOPool.t.sol asserts on-chain root == JS root after each of 8
 *   sequential inserts, plus raw Poseidon2 equivalence vectors. The remaining
 *   residual gap (irreducible pre-ceremony): equivalence to the CIRCUIT's
 *   LeanIMTInclusionProof root end-to-end needs a real proof, confirmed at the
 *   post-ceremony Sepolia smoke. The Groth16 verifier is still unwired here
 *   (mock returns true) until the ceremony pins the vkey.
 */

interface IGroth16Verifier {
    /**
     * Standard Groth16 verifier ABI as generated by snarkjs.
     * The vkey is baked into the deployed verifier — different vkey ⇒ different
     * contract address. We reuse the *interface* but a new `Verifier_NoteSpend`
     * contract has to be deployed after the trusted-setup ceremony completes.
     *
     * The 8 public signals (v1 layout, in snarkjs emit order — outputs first,
     * then the `public [...]` inputs of `NoteSpend(32,2,2)`):
     *   [0..1] nullifierHashes[0..1]
     *   [2..3] outputCommitments[0..1]
     *   [4]    stateRoot
     *   [5]    stateTreeDepth
     *   [6]    aspRoot
     *   [7]    context
     *
     * v1 removed `withdrawnAmount` and `aspTreeDepth` from the public set (both
     * are now private witnesses). `withdrawnAmount` is bound to the on-chain
     * `unshieldAmount` calldata via `context` (Railgun pattern): the circuit
     * asserts `withdrawnAmount == the value committed in context`, so the
     * contract pays out the calldata amount and the context check proves the
     * proof used that same number. See `circuits/note_spend.circom` header.
     */
    function verifyProof(
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256[8] calldata pubSignals
    ) external view returns (bool);
}

interface IEntrypoint {
    /** ASP root; identical to the entrypoint already deployed for the V0 pool. */
    function latestRoot() external view returns (uint256);
}

interface IERC20 {
    function transfer(address to, uint256 amount) external returns (bool);
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
}

contract UTXOPool is ReentrancyGuard {
    // -------------------------------------------------------------------------
    // Configuration
    // -------------------------------------------------------------------------

    /// Groth16 verifier contract — must be the one produced by the `note_spend`
    /// circuit's trusted-setup ceremony. Different vkey ⇒ different bytecode.
    /// TODO: ceremony — set to deployed `Verifier_NoteSpend` address.
    address public immutable VERIFIER;

    /// ASP root oracle + authorized caller for `spend()`. In production this is
    /// the ThresholdEntrypoint (B.2) which both publishes the ASP root and
    /// drives withdrawals after off-chain proof gen. Locked at deploy — same
    /// `ENTRYPOINT = msg.sender at deploy` pattern as `PrivacyPoolMorpho`
    /// would mismatch here, because the entrypoint is the ASP oracle (a
    /// separate contract), not the deployer. So we take it as a constructor
    /// argument and store immutably.
    address public immutable ENTRYPOINT;

    /// USDC token (Base Sepolia: 0x036CbD53842c5426634e7929541eC2318f3dCF7e,
    /// Base mainnet: 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913). Set at
    /// deploy from a constructor argument — Phase 1A unwired-to-wired fix.
    address public immutable TOKEN;

    /// Scope: keccak256(poolId || tokenAddress) — a domain separator for
    /// commitments / labels. Mirrors the V0 pool's SCOPE; MUST differ so the
    /// two anonymity sets remain disjoint (a single nullifier in V0 must not
    /// pre-spend a UTXO commitment, and vice versa).
    uint256 public immutable SCOPE;

    /// BN254 scalar field modulus. Public inputs are reduced into this field.
    uint256 internal constant SNARK_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// Rolling buffer size for accepted state roots. The V0 pool uses 32;
    /// UTXO commitments are inserted at a higher per-spend rate (2 leaves per
    /// spend instead of 1) so we widen to 64 to keep the same effective time
    /// window for stale-root tolerance.
    uint256 internal constant STATE_ROOT_HISTORY = 64;

    /// Maximum LeanIMT depth. Matches `note_spend.circom`'s `maxTreeDepth` (32),
    /// so the circuit's fixed-depth inclusion proof can verify any root this
    /// contract produces. A depth-32 LeanIMT holds up to 2^32 leaves — far
    /// beyond any realistic anonymity-set size. Inserts revert if a tree would
    /// exceed this depth (cannot happen below 2^32 leaves).
    uint256 internal constant MAX_TREE_DEPTH = 32;

    /// Domain separator for transfer-flow context binding. Picked so that a
    /// `spend()` proof and a `transfer()` proof can never share the same
    /// context value even if all other public signals coincided — `spend()`
    /// derives context from `keccak256(withdrawal, SCOPE)`, `transfer()`
    /// derives it from `keccak256(TRANSFER_CONTEXT_TAG, SCOPE)`. With
    /// `withdrawal` being a (address, bytes) ABI-encoded tuple, no spend
    /// context can collide with a transfer context whose preimage is a
    /// single fixed bytes32 + uint256.
    bytes32 internal constant TRANSFER_CONTEXT_TAG =
        keccak256("zbase.utxo.transfer.v1");

    // -------------------------------------------------------------------------
    // State
    // -------------------------------------------------------------------------

    /// Nullifier-spent set. Each `Poseidon1(nullifier)` flips to true once
    /// consumed in a spend. Critical: replay protection.
    mapping(uint256 => bool) public spentNullifierHashes;

    /// Recent accepted state roots (rolling ring buffer). Populated by
    /// `_insertLeaf`. Reads via `_isKnownRoot`.
    uint256[STATE_ROOT_HISTORY] public stateRoots;

    /// Next write slot in `stateRoots`. The ring buffer is "full" once
    /// `leafCount >= STATE_ROOT_HISTORY` — older entries are overwritten.
    uint256 public rootIndex;

    /// Number of commitments inserted so far. Equals the index of the next
    /// leaf (LeanIMT leaves are appended at `leafCount`). Also doubles as the
    /// "have we ever inserted anything" guard for `_isKnownRoot`.
    uint256 public leafCount;

    /// The current (latest) state root — the canonical Poseidon2-LeanIMT root
    /// over all inserted leaves (matches the JS zk-kit lean-imt reference and
    /// `note_spend.circom` LeanIMTInclusionProof). On a fresh pool this is 0;
    /// the first insert produces a non-zero root (= the single leaf itself).
    uint256 public currentRoot;

    /// Current LeanIMT depth (number of levels - 1). Exposed so the circuit's
    /// `stateTreeDepth` public signal can be checked against the live tree.
    uint256 public treeDepth;

    /// LeanIMT incremental "side nodes" (the frontier): `sideNodes[level]` holds
    /// the left node at `level` that a future right-child insert at that level
    /// will hash against. This is the minimal O(depth) state needed to advance
    /// the root on each append without storing the whole tree. Mirrors the
    /// `_nodes[level][index]` left-sibling reads in zk-kit's `LeanIMT.insert`.
    mapping(uint256 => uint256) public sideNodes;

    // -------------------------------------------------------------------------
    // Events
    // -------------------------------------------------------------------------

    /// Mirror of the V0 pool's event so the indexer doesn't need a separate path.
    event LeafInserted(uint256 indexed index, uint256 leaf, uint256 root);

    /// Encrypted-note off-chain payload, scoped to its commitment.
    /// Recipient wallets/facilitators scan for these.
    event NoteCommitted(uint256 indexed commitment, bytes encryptedNote);

    /// Per-spend record: amount paid out + the new commitments. Replaces the
    /// V0 pool's `Withdrawn` event. Recipient is *not* indexed by design —
    /// indexing it would defeat amount-hiding by making per-recipient sums
    /// trivially queryable.
    event Spent(
        uint256 indexed nullifierHash0,
        uint256 indexed nullifierHash1,
        uint256 withdrawnAmount,
        uint256 outputCommitment0,
        uint256 outputCommitment1
    );

    /// Per-transfer record: no USDC moved, only commitments + nullifiers +
    /// per-output ciphertexts. Mirrors `Spent` shape minus `withdrawnAmount`
    /// (always 0 for transfers, enforced by `_checkTransferShape`) and minus
    /// any recipient (transfers settle entirely inside the pool).
    ///
    /// The CommitmentCiphertext fields are emitted in-band so a scanner reading
    /// only `Transferred` events can decrypt without a second NoteCommitted hop.
    /// Each ciphertext's `aad` MUST equal `keccak256(abi.encode(outputCommitment[i]))`
    /// — the contract enforces this in `transfer()` so a malicious relayer can't
    /// shuffle ciphertexts between commitments in the same block (Phase 1B Fix 3).
    event Transferred(
        uint256 indexed nullifierHash0,
        uint256 indexed nullifierHash1,
        uint256 outputCommitment0,
        uint256 outputCommitment1,
        CommitmentCiphertext ciphertext0,
        CommitmentCiphertext ciphertext1
    );

    // -------------------------------------------------------------------------
    // Types
    // -------------------------------------------------------------------------

    /// Mirrors the V0 pool's `Withdrawal` struct (see Entrypoint.sol). Bound
    /// into `context` via keccak256(abi.encode(withdrawal, scope)) % SNARK_FIELD.
    struct Withdrawal {
        address processooor;
        bytes data; // ABI-encoded { recipient, feeRecipient, relayFeeBPS }
    }

    /// Standard Groth16 proof from snarkjs. pi_b coordinates are pre-swapped
    /// by the caller (see existing /api/withdraw/route.ts:386-401 for the
    /// same Fp2 swap pattern — applies identically to the UTXO circuit).
    struct Proof {
        uint256[2] pA;
        uint256[2][2] pB;
        uint256[2] pC;
        uint256[8] pubSignals; // v1: 8-signal layout (see IGroth16Verifier doc)
    }

    /// Off-chain encrypted note payload + per-commitment AAD binding.
    ///
    /// Shape mirrors Railgun's `Globals.sol:31` CommitmentCiphertext struct
    /// (`bytes32[4] ciphertext`, two blinded viewing keys, a memo) with one
    /// addition: an explicit `aad` field. The SDK MUST set
    ///   aad = keccak256(abi.encode(outputCommitment))
    /// and pass the same value as XChaCha20-Poly1305's AAD parameter when
    /// encrypting `ciphertext`. The contract re-derives + checks the AAD in
    /// `transfer()` (Phase 1B Fix 3) so a malicious relayer cannot pair
    /// proof A's commitments with proof B's ciphertexts inside one block.
    ///
    /// `ciphertext` is the SDK's variable-length XChaCha20-Poly1305 envelope
    /// (`packages/core/src/notes.ts` `EncryptedNote`: [ephPub:32|viewTag:2|
    /// nonce:24|AEAD ct+tag]). Widened from Railgun's fixed `bytes32[4]` (128B)
    /// to `bytes` because zBase's envelope (~208B) does not fit four words — the
    /// original fixed-slot Railgun layout assumed a fixed-size plaintext.
    /// The CONTRACT does NOT parse `ciphertext`; it only re-derives + checks `aad`
    /// (see `transfer()` Fix 3). The bytes are opaque passthrough emitted in
    /// `Transferred` for the recipient scanner to decode (SDK `unpackCiphertext`).
    struct CommitmentCiphertext {
        bytes ciphertext;
        bytes32 blindedSenderViewingKey;
        bytes32 blindedReceiverViewingKey;
        bytes32 memo;
        bytes32 aad;
    }

    // -------------------------------------------------------------------------
    // Errors
    // -------------------------------------------------------------------------

    error InvalidProof();
    error UnknownStateRoot();
    error IncorrectASPRoot();
    error NullifierAlreadySpent();
    error ContextMismatch();
    error InvalidWithdrawalAmount();
    /// Transfer-specific: the proof's `withdrawnAmount` public signal must be 0.
    /// If non-zero, the SDK is trying to unshield via the transfer dispatch
    /// path — caller should use `spend()` instead.
    /// @dev v1: no longer thrown — `withdrawnAmount` left the public signals and
    /// transfer() performs no payout regardless. Retained for ABI/selector
    /// stability + decoders; the soundly-zero guarantee returns with the C4 fix.
    error TransferMustBeZeroAmount();
    /// Transfer-specific: ciphertext.aad does not equal
    /// keccak256(abi.encode(outputCommitment[i])). Indicates ciphertext shuffle
    /// by a malicious relayer; Fix 3 in the Phase 1B plan.
    error CiphertextAADMismatch();

    // -------------------------------------------------------------------------
    // Access control
    // -------------------------------------------------------------------------

    /// Matches `PrivacyPoolMorpho.onlyEntrypoint`. An unrestricted public
    /// `spend()` would let anyone with a valid proof drain the pool to an
    /// attacker-controlled recipient; in production the ENTRYPOINT is the
    /// only contract permitted to compose proof gen + relay payment.
    modifier onlyEntrypoint() {
        require(msg.sender == ENTRYPOINT, "NOT_ENTRYPOINT");
        _;
    }

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    constructor(
        address _verifier,
        address _entrypoint,
        address _token,
        uint256 _scope
    ) {
        require(_entrypoint != address(0), "ENTRYPOINT=0");
        require(_token != address(0), "TOKEN=0");
        // F9: the verifier MUST be a contract. Pre-fix the constructor accepted
        // any address, including address(0) or an EOA — a call to which returns
        // false (so spend/transfer would revert), but more importantly there was
        // no guard against shipping a pool whose VERIFIER doesn't actually verify
        // proofs. Requiring code at the address stops the address(0)/EOA-to-
        // mainnet footgun. A *mock* verifier still passes (it has code) for tests;
        // the mainnet checklist must additionally confirm VERIFIER is the
        // ceremony-produced verifier, which is an off-chain deploy-time gate.
        require(_verifier.code.length > 0, "VERIFIER_NOT_CONTRACT");

        VERIFIER = _verifier;
        ENTRYPOINT = _entrypoint;
        TOKEN = _token;
        SCOPE = _scope;
    }

    // -------------------------------------------------------------------------
    // Deposit-side hook
    // -------------------------------------------------------------------------

    /**
     * Insert a single (already Poseidon-hashed off-chain) commitment into
     * the state tree. Mirrors the V0 pool's `deposit` post-fee insert path,
     * minus the USDC pull (the Entrypoint pulls funds itself and forwards
     * the commitment hash). Used by the indexer + test harness to bootstrap
     * an anonymity set before any spend is exercised.
     *
     * Gated to ENTRYPOINT only — an open `deposit()` would let anyone bloat
     * the state tree with junk leaves.
     */
    function deposit(uint256 commitment, bytes calldata encryptedNote)
        external
        onlyEntrypoint
        nonReentrant
    {
        _insertLeaf(commitment);
        emit NoteCommitted(commitment, encryptedNote);
    }

    // -------------------------------------------------------------------------
    // Spend — the only money-moving entrypoint
    // -------------------------------------------------------------------------

    /**
     * Consume 2 input notes (by nullifier hash), mint 2 output notes (by
     * commitment), optionally transfer `withdrawnAmount` of TOKEN to a recipient
     * bound into the proof.
     *
     * @param withdrawal       Recipient binding struct (matches V0 pool layout).
     * @param proof            Groth16 proof with 8 public signals (v1 layout) in
     *                         the order declared by `note_spend.circom`.
     * @param encryptedOutputNotes  Off-chain ciphertexts (post via NoteCommitted).
     *                              Length MUST be 2; relayer/wallet pads with
     *                              empty bytes for dummy outputs.
     */
    function spend(
        Withdrawal calldata withdrawal,
        Proof calldata proof,
        bytes[2] calldata encryptedOutputNotes
    ) external onlyEntrypoint nonReentrant {
        // ----- 1. Context + ASP + state-root preconditions ------------------
        _checkContextAndRoots(withdrawal, proof);

        // ----- 2. Verify the Groth16 proof FIRST (audit F3) -----------------
        // The proof MUST be verified before nullifiers are marked spent.
        // Marking-then-verifying let an invalid proof permanently burn a valid
        // nullifier (the revert undoes nothing of value to the griefer but makes
        // the real owner's note unwithdrawable). Verify → revert-on-bad → only
        // then consume.
        // TODO: ceremony — VERIFIER points at a contract whose vkey was
        // produced by the trusted-setup ceremony for note_spend.circom.
        if (
            !IGroth16Verifier(VERIFIER).verifyProof(
                proof.pA, proof.pB, proof.pC, proof.pubSignals
            )
        ) revert InvalidProof();

        // ----- 3. Nullifier double-spend check (only after a valid proof) ---
        _consumeNullifiers(proof.pubSignals[0], proof.pubSignals[1]);

        // ----- 4. Insert output commitments into the state tree -------------
        _insertLeaf(proof.pubSignals[2]);
        _insertLeaf(proof.pubSignals[3]);

        // ----- 5. Post encrypted note ciphertexts + Spent event -------------
        emit NoteCommitted(proof.pubSignals[2], encryptedOutputNotes[0]);
        emit NoteCommitted(proof.pubSignals[3], encryptedOutputNotes[1]);
        emit Spent(
            proof.pubSignals[0],
            proof.pubSignals[1],
            0, // unshield amount — PARKED (see C4 below); 0 until the binding is sound
            proof.pubSignals[2],
            proof.pubSignals[3]
        );

        // ----- 6. Unshield (USDC payout) — PARKED ON AUDIT FINDING C4 --------
        //
        // ⚠️ v1 SOUNDNESS GAP (docs/security/internal-audit-2026-06-11.md → C4):
        //   v1 made `withdrawnAmount` a PRIVATE witness and claims it is bound to
        //   an on-chain `unshieldAmount` via `context`. In the FROZEN circuit that
        //   binding is a NO-OP (note_spend.circom:310-317 compute dead squares with
        //   no constraint), and the contract cannot enforce it either (the witness
        //   is private — never seen on-chain). There is therefore NO sound source
        //   for a payout amount: paying out a calldata field would be unconstrained
        //   relative to the proof. `withdrawal.data` also has no amount field today
        //   (`{recipient, feeRecipient, relayFeeBPS}`).
        //
        //   We deliberately DO NOT pay out here. Re-enable ONLY after the external
        //   auditor + post-freeze fix makes the amount sound (e.g. re-expose
        //   `withdrawnAmount` as a public signal, then read it from pubSignals and
        //   transfer to the recipient). Until then a `spend()` mints output notes
        //   (internal value movement) but performs NO unshield — a transfer-only
        //   spend, which is safe. The single-value pool's withdraw path is unaffected.
        //
        // TODO(C4 + ceremony): once `withdrawnAmount` is a sound public signal,
        //   restore: `if (amt>0) { decode recipient; IERC20(TOKEN).transfer(...); }`
        //   and emit it in `Spent`. For the Morpho-yield variant, _redeem first.
    }

    /// Hoisted to keep `spend()` under the Solidity stack-frame limit.
    /// Verifies (1) context binding, (2) state root is in the recent window,
    /// (3) the proof's ASP root matches the entrypoint's published latest.
    function _checkContextAndRoots(
        Withdrawal calldata withdrawal,
        Proof calldata proof
    ) internal view {
        // Same recipe as src/app/api/withdraw/route.ts. v1 8-signal layout:
        // [4]=stateRoot, [5]=stateTreeDepth, [6]=aspRoot, [7]=context.
        uint256 expectedContext = uint256(
            keccak256(abi.encode(withdrawal, SCOPE))
        ) % SNARK_FIELD;
        if (proof.pubSignals[7] != expectedContext) revert ContextMismatch();

        if (!_isKnownRoot(proof.pubSignals[4])) revert UnknownStateRoot();

        // TODO: integrate — once threshold-postman B.2 ships, allow a small
        // window of recent ASP roots instead of strict equality.
        if (proof.pubSignals[6] != IEntrypoint(ENTRYPOINT).latestRoot()) {
            revert IncorrectASPRoot();
        }
    }

    /// Hoisted to keep `spend()` under the Solidity stack-frame limit.
    /// Output dummies (input.amount=0, dummy=1) yield distinct random
    /// nullifier hashes in the circuit, so collision between the two slot
    /// nullifiers can only happen if a malicious prover supplies the same
    /// nullifier in both slots — the circuit's distinct random secret rule
    /// does NOT prevent this, so we enforce it here.
    function _consumeNullifiers(uint256 n0, uint256 n1) internal {
        if (spentNullifierHashes[n0]) revert NullifierAlreadySpent();
        if (n0 == n1) revert NullifierAlreadySpent();
        if (spentNullifierHashes[n1]) revert NullifierAlreadySpent();
        spentNullifierHashes[n0] = true;
        spentNullifierHashes[n1] = true;
    }

    // -------------------------------------------------------------------------
    // Transfer — pool-internal value movement, no USDC leaves the pool
    // -------------------------------------------------------------------------

    /**
     * Pool-internal note transfer. Identical proof + conservation +
     * ASP-membership + nullifier-not-spent constraints as `spend()`, but the
     * proof's `withdrawnAmount` public signal MUST be 0 (no USDC leaves the
     * pool) and the per-output ciphertexts are emitted on-chain in the
     * `Transferred` event so the receiver can scan + decrypt.
     *
     * The same Groth16 verifier is used as `spend()` — Agent CIRCUIT made
     * `note_spend.circom` identical for both ops by removing the dispatch
     * flag. The only on-chain difference between the two paths is:
     *   - `spend()` reads `withdrawnAmount > 0` and transfers TOKEN out.
     *   - `transfer()` enforces `withdrawnAmount == 0` and skips the transfer.
     *
     * AAD binding (Phase 1B Fix 3): each ciphertext's `aad` field MUST equal
     * `keccak256(abi.encode(outputCommitment[i]))`. The SDK uses the same value
     * as XChaCha20-Poly1305's AAD parameter when encrypting the payload, so
     * decryption fails downstream if the ciphertext was paired with the wrong
     * commitment. We verify on-chain to also fail the on-chain submission —
     * relayers cannot shuffle ciphertexts between proofs in the same block.
     *
     * @param proof        Groth16 proof — same 8-signal (v1) layout as `spend()`.
     * @param ciphertexts  Per-output encrypted-note payloads with AAD binding.
     */
    function transfer(
        Proof calldata proof,
        CommitmentCiphertext[2] calldata ciphertexts
    ) external onlyEntrypoint nonReentrant {
        // ----- 1. Transfer shape ---------------------------------------------
        // v1: `withdrawnAmount` is no longer a public signal, so the old
        // `pubSignals[4]==0` check is gone. A transfer is structurally an
        // unshield of zero — and transfer() performs NO USDC payout at all
        // (see step 7), so even a nonzero private withdrawnAmount cannot move
        // funds out here. The transfer-domain `context` tag (checked below)
        // separates transfer proofs from spend proofs. (Soundly tying the
        // private withdrawnAmount to zero for transfers is part of the C4
        // circuit fix — see docs/security/internal-audit-2026-06-11.md.)

        // ----- 2. ASP + state-root + context preconditions ------------------
        _checkTransferContextAndRoots(proof);

        // ----- 3. Verify the Groth16 proof FIRST (audit F3) -----------------
        // Verify before consuming nullifiers, so an invalid proof can never
        // permanently burn a valid nullifier (see spend() for the rationale).
        // Same verifier contract as `spend()` (per the unified circuit).
        if (
            !IGroth16Verifier(VERIFIER).verifyProof(
                proof.pA, proof.pB, proof.pC, proof.pubSignals
            )
        ) revert InvalidProof();

        // ----- 4. Nullifier double-spend check (only after a valid proof) ---
        _consumeNullifiers(proof.pubSignals[0], proof.pubSignals[1]);

        // ----- 5. AAD binding check (Fix 3) ---------------------------------
        // Re-derive the expected AAD from each output commitment and compare
        // against the ciphertext-supplied AAD. Mismatch => relayer is trying
        // to swap ciphertexts between commitments; revert before any state
        // mutation that an indexer would observe.
        bytes32 expectedAAD0 =
            keccak256(abi.encode(proof.pubSignals[2]));
        bytes32 expectedAAD1 =
            keccak256(abi.encode(proof.pubSignals[3]));
        if (ciphertexts[0].aad != expectedAAD0) revert CiphertextAADMismatch();
        if (ciphertexts[1].aad != expectedAAD1) revert CiphertextAADMismatch();

        // ----- 6. Insert output commitments into the state tree -------------
        _insertLeaf(proof.pubSignals[2]);
        _insertLeaf(proof.pubSignals[3]);

        // ----- 7. Emit the Transferred event with both ciphertexts ----------
        // No NoteCommitted hop — the ciphertexts are in-band so scanners only
        // need to follow Transferred.
        emit Transferred(
            proof.pubSignals[0],
            proof.pubSignals[1],
            proof.pubSignals[2],
            proof.pubSignals[3],
            ciphertexts[0],
            ciphertexts[1]
        );

        // NOTE: deliberately no USDC transfer — transfer is pool-internal.
        // The pool's USDC balance is unchanged across this call.
    }

    /// Hoisted to keep `transfer()` under the stack-frame limit. Mirror of
    /// `_checkContextAndRoots` but with the transfer-specific context recipe
    /// (no `Withdrawal` struct — context binds to the fixed domain tag).
    function _checkTransferContextAndRoots(Proof calldata proof) internal view {
        // v1 8-signal layout: [4]=stateRoot, [6]=aspRoot, [7]=context.
        uint256 expectedContext = uint256(
            keccak256(abi.encode(TRANSFER_CONTEXT_TAG, SCOPE))
        ) % SNARK_FIELD;
        if (proof.pubSignals[7] != expectedContext) revert ContextMismatch();

        if (!_isKnownRoot(proof.pubSignals[4])) revert UnknownStateRoot();

        if (proof.pubSignals[6] != IEntrypoint(ENTRYPOINT).latestRoot()) {
            revert IncorrectASPRoot();
        }
    }

    /// Public helper so off-chain SDK + tests can compute the same context
    /// the contract enforces. Pure view — no state.
    function transferContext() external view returns (uint256) {
        return uint256(
            keccak256(abi.encode(TRANSFER_CONTEXT_TAG, SCOPE))
        ) % SNARK_FIELD;
    }

    // -------------------------------------------------------------------------
    // Internals
    // -------------------------------------------------------------------------

    /**
     * `root` is "known" if it appears in the rolling buffer of recent roots.
     * Reverts on `root == 0` (the fresh-pool sentinel) — no spend can ever
     * reference the empty tree because no commitments exist in it.
     */
    function _isKnownRoot(uint256 root) internal view returns (bool) {
        if (root == 0) return false;
        if (leafCount == 0) return false;
        // Walk only the populated portion of the buffer. Once leafCount
        // exceeds STATE_ROOT_HISTORY the whole buffer is live; before that
        // unwritten slots are still zero (never matchable since we excluded
        // root == 0 above, but skipping them is faster).
        uint256 bound = leafCount < STATE_ROOT_HISTORY ? leafCount : STATE_ROOT_HISTORY;
        for (uint256 i = 0; i < bound; i++) {
            if (stateRoots[i] == root) return true;
        }
        return false;
    }

    /**
     * Insert a commitment into the Poseidon2-LeanIMT state tree and advance the
     * root, pushing the new root into the rolling history buffer.
     *
     * LeanIMT incremental append (mirrors zk-kit `LeanIMT.insert` exactly):
     *   - leaves are appended at index `leafCount`;
     *   - the depth grows to `ceil(log2(size+1))` levels;
     *   - walking up from the leaf: while the current node is a RIGHT child
     *     (index bit 1) hash it against the saved left `sideNodes[level]` and
     *     continue up; once it is a LEFT child (bit 0) save it as the new
     *     `sideNodes[level]` (the frontier a future right sibling will hash
     *     against) and STOP updating frontiers — the node then propagates
     *     unchanged up the remaining levels to become the root (the "no right
     *     sibling → parent = left child" rule, no zero padding).
     *
     * Why save-then-stop (not save-at-every-left-level): a leaf with lowest set
     * bit at position b is a right child at levels 0..b-1 and a left child at
     * level b. It is the frontier ONLY at level b; above that it is merely the
     * running root value (left-promoted), not a node any later insert hashes
     * against. Saving it at higher levels too would clobber genuine frontiers
     * from earlier subtrees. The first leaf (idx 0) is a pure left child: it
     * saves sideNodes[0] and is itself the depth-0 root. This is exactly what
     * zk-kit's `_nodes[level][index]` bookkeeping does — verified against the
     * JS reference root after each insert in UTXOPool.t.sol.
     *
     * The hash is Poseidon2 (PoseidonT3.hash), byte-identical to circomlib /
     * poseidon-lite (the JS reference + `note_spend.circom`), so the root this
     * produces equals the JS zk-kit lean-imt root for the same leaves
     * (asserted in UTXOPool.t.sol) and the circuit's LeanIMTInclusionProof
     * verifies against it.
     *
     * NOTE (auditor-scoped, pre-ceremony): equivalence to the JS LeanIMT
     * reference is tested here; equivalence to the CIRCUIT root end-to-end is
     * confirmed at the post-ceremony Sepolia smoke (needs a real proof). That
     * residual gap is irreducible until the ceremony zkey exists.
     */
    function _insertLeaf(uint256 leaf) internal {
        uint256 idx = leafCount;
        // Leaves are circuit inputs; keep them in-field (a commitment from a
        // valid proof always is, but deposit() takes a raw commitment arg).
        require(leaf < SNARK_FIELD, "leaf >= SNARK_FIELD");

        // New depth after this insert = ceil(log2(size + 1)). For the first leaf
        // (size 0 -> 1) depth stays 0 and the root is the leaf itself.
        uint256 size = idx + 1;
        uint256 newDepth = _ceilLog2(size);
        require(newDepth <= MAX_TREE_DEPTH, "tree depth exceeds MAX_TREE_DEPTH");

        // Climb from the leaf to the root, maintaining the per-level frontier.
        // `sideNodes[level]` parks the left node at `level` awaiting a right
        // sibling. At each level the leaf's path bit decides:
        //   bit 1 (right child) → parent = hash(parked left sibling, node);
        //   bit 0 (left child)  → park this node as the new frontier; it carries
        //                         up unchanged (LeanIMT left-promotion).
        // The running `node` after `newDepth` levels is the root.
        uint256 node = leaf;
        uint256 index = idx;
        for (uint256 level = 0; level < newDepth; level++) {
            if (index & 1 == 1) {
                node = PoseidonT3.hash([sideNodes[level], node]);
            } else {
                sideNodes[level] = node;
            }
            index >>= 1;
        }
        // The root itself is a left child at level `newDepth` (it has no right
        // sibling yet). Park it so the NEXT insert that grows the tree depth has
        // a left sibling to hash its new subtree against. This single line is
        // what the in-loop frontier saves miss: for a perfect tree
        // (idx == 2^newDepth - 1, e.g. idx 0,1,3,7,…) every loop level is a
        // right-child hash and no frontier is parked inside the loop, yet the
        // root must be available as `sideNodes[newDepth]` for the depth-growing
        // insert. It also seeds `sideNodes[0]` for the very first leaf (newDepth
        // 0, loop never runs). Verified against the JS zk-kit reference root
        // after each of 8 inserts in UTXOPool.t.sol.
        sideNodes[newDepth] = node;

        leafCount = size;
        treeDepth = newDepth;
        currentRoot = node;

        // Push into the rolling buffer (wraps modulo STATE_ROOT_HISTORY).
        uint256 slot = rootIndex;
        stateRoots[slot] = node;
        rootIndex = (slot + 1) % STATE_ROOT_HISTORY;

        emit LeafInserted(idx, leaf, node);
    }

    /// Smallest `d` such that `2^d >= n` (= ceil(log2(n))). `_ceilLog2(1) == 0`.
    /// Matches `Math.ceil(Math.log2(size + 1))` in zk-kit's LeanIMT.insert for
    /// the depth-growth check (there `size` is pre-insert; here we pass the
    /// post-insert size, giving the identical resulting depth).
    function _ceilLog2(uint256 n) internal pure returns (uint256) {
        if (n <= 1) return 0;
        uint256 d = 0;
        uint256 p = 1;
        while (p < n) {
            p <<= 1;
            d++;
        }
        return d;
    }
}
